// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `authentication` resource.

#[derive(Clone)]
pub struct Authentication {
    client: crate::client::Scalar,
}

impl Authentication {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// Exchange token
    pub fn exchange_personal_token(&self, body: crate::models::AuthenticationExchangePersonalTokenBody) -> ExchangePersonalTokenRequest {
        ExchangePersonalTokenRequest::new(self.client.clone(), body)
    }

    /// Get current user
    pub fn list_current_user(&self) -> ListCurrentUserRequest {
        ListCurrentUserRequest::new(self.client.clone())
    }
}

/// Exchange an API key for an access token.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ExchangePersonalTokenRequest {
    client: crate::client::Scalar,
    body: crate::models::AuthenticationExchangePersonalTokenBody,
    idempotency_key: Option<String>,
}

impl ExchangePersonalTokenRequest {
    fn new(client: crate::client::Scalar, body: crate::models::AuthenticationExchangePersonalTokenBody) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::AuthenticationExchangePersonalTokenResponse, crate::error::Error> {
        let path = "/v1/auth/exchange".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<crate::models::AuthenticationExchangePersonalTokenResponse, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
/// Get the authenticated user, including their available teams and theme.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListCurrentUserRequest {
    client: crate::client::Scalar,
}

impl ListCurrentUserRequest {
    fn new(client: crate::client::Scalar) -> Self {
        Self {
            client,
        }
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::User, crate::error::Error> {
        let path = "/v1/auth/me".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<crate::models::User, _>(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
