// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `loginPortals` resource.

#[derive(Clone)]
pub struct LoginPortals {
    client: crate::client::Scalar,
}

impl LoginPortals {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// Get a login portal
    pub fn retrieve(&self, slug: impl Into<String>) -> RetrieveRequest {
        RetrieveRequest::new(self.client.clone(), slug.into())
    }

    /// Update portal metadata
    pub fn update(&self, slug: impl Into<String>, body: crate::models::LoginPortalsUpdateBody) -> UpdateRequest {
        UpdateRequest::new(self.client.clone(), slug.into(), body)
    }

    /// Delete a login portal
    pub fn delete(&self, slug: impl Into<String>) -> DeleteRequest {
        DeleteRequest::new(self.client.clone(), slug.into())
    }

    /// Create a portal
    pub fn create(&self, body: crate::models::LoginPortalsCreateBody) -> CreateRequest {
        CreateRequest::new(self.client.clone(), body)
    }

    /// List all portals
    pub fn list(&self) -> ListRequest {
        ListRequest::new(self.client.clone())
    }
}

/// Get a login portal by slug.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveRequest {
    client: crate::client::Scalar,
    slug: String,
}

impl RetrieveRequest {
    fn new(client: crate::client::Scalar, slug: String) -> Self {
        Self {
            client,
            slug,
        }
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::LoginPortalsRetrieveResponse, crate::error::Error> {
        let path = format!("/v1/login-portals/{}", crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<crate::models::LoginPortalsRetrieveResponse, _>(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
/// Update metadata for a login portal.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateRequest {
    client: crate::client::Scalar,
    slug: String,
    body: crate::models::LoginPortalsUpdateBody,
    idempotency_key: Option<String>,
}

impl UpdateRequest {
    fn new(client: crate::client::Scalar, slug: String, body: crate::models::LoginPortalsUpdateBody) -> Self {
        Self {
            client,
            slug,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/login-portals/{}", crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<serde_json::Value, _>(reqwest::Method::PATCH, &path, &query, &headers, body, true)
            .await
    }
}
/// Delete a login portal.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteRequest {
    client: crate::client::Scalar,
    slug: String,
    idempotency_key: Option<String>,
}

impl DeleteRequest {
    fn new(client: crate::client::Scalar, slug: String) -> Self {
        Self {
            client,
            slug,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/login-portals/{}", crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<serde_json::Value, _>(reqwest::Method::DELETE, &path, &query, &headers, body, true)
            .await
    }
}
/// Create a login portal for the current team.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRequest {
    client: crate::client::Scalar,
    body: crate::models::LoginPortalsCreateBody,
    idempotency_key: Option<String>,
}

impl CreateRequest {
    fn new(client: crate::client::Scalar, body: crate::models::LoginPortalsCreateBody) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::Uid, crate::error::Error> {
        let path = "/v1/login-portals".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<crate::models::Uid, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
/// List all login portals for the current team.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRequest {
    client: crate::client::Scalar,
}

impl ListRequest {
    fn new(client: crate::client::Scalar) -> Self {
        Self {
            client,
        }
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<Vec<crate::models::LoginPortal>, crate::error::Error> {
        let path = "/v1/login-portals".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<Vec<crate::models::LoginPortal>, _>(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
