// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Resource sub-clients and root accessors.

pub mod registry;
pub mod schemas;
pub mod version;
pub mod access_group;
pub mod login_portals;
pub mod rules;
pub mod themes;
pub mod teams;
pub mod scalar_docs;
pub mod namespaces;
pub mod authentication;

impl crate::client::Scalar {
    pub fn registry(&self) -> crate::resources::registry::Registry {
        crate::resources::registry::Registry::new(self.clone())
    }

    pub fn schemas(&self) -> crate::resources::schemas::Schemas {
        crate::resources::schemas::Schemas::new(self.clone())
    }

    pub fn login_portals(&self) -> crate::resources::login_portals::LoginPortals {
        crate::resources::login_portals::LoginPortals::new(self.clone())
    }

    pub fn rules(&self) -> crate::resources::rules::Rules {
        crate::resources::rules::Rules::new(self.clone())
    }

    pub fn themes(&self) -> crate::resources::themes::Themes {
        crate::resources::themes::Themes::new(self.clone())
    }

    pub fn teams(&self) -> crate::resources::teams::Teams {
        crate::resources::teams::Teams::new(self.clone())
    }

    pub fn scalar_docs(&self) -> crate::resources::scalar_docs::ScalarDocs {
        crate::resources::scalar_docs::ScalarDocs::new(self.clone())
    }

    pub fn namespaces(&self) -> crate::resources::namespaces::Namespaces {
        crate::resources::namespaces::Namespaces::new(self.clone())
    }

    pub fn authentication(&self) -> crate::resources::authentication::Authentication {
        crate::resources::authentication::Authentication::new(self.clone())
    }
}
