// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Resource sub-clients and root accessors.

pub mod access_group;
pub mod authentication;
pub mod login_portals;
pub mod namespaces;
pub mod registry;
pub mod rules;
pub mod scalar_docs;
pub mod schemas;
pub mod teams;
pub mod themes;
pub mod version;

impl crate::client::Scalar {
    /// Registry
    pub fn registry(&self) -> crate::resources::registry::RegistryResource {
        crate::resources::registry::RegistryResource::new(self.clone())
    }

    /// Schemas
    pub fn schemas(&self) -> crate::resources::schemas::SchemasResource {
        crate::resources::schemas::SchemasResource::new(self.clone())
    }

    /// Login Portals
    pub fn login_portals(&self) -> crate::resources::login_portals::LoginPortalsResource {
        crate::resources::login_portals::LoginPortalsResource::new(self.clone())
    }

    /// Rules
    pub fn rules(&self) -> crate::resources::rules::RulesResource {
        crate::resources::rules::RulesResource::new(self.clone())
    }

    /// Themes
    pub fn themes(&self) -> crate::resources::themes::ThemesResource {
        crate::resources::themes::ThemesResource::new(self.clone())
    }

    /// Teams
    pub fn teams(&self) -> crate::resources::teams::TeamsResource {
        crate::resources::teams::TeamsResource::new(self.clone())
    }

    /// Scalar Docs
    pub fn scalar_docs(&self) -> crate::resources::scalar_docs::ScalarDocsResource {
        crate::resources::scalar_docs::ScalarDocsResource::new(self.clone())
    }

    /// Namespaces
    pub fn namespaces(&self) -> crate::resources::namespaces::NamespacesResource {
        crate::resources::namespaces::NamespacesResource::new(self.clone())
    }

    /// Authentication
    pub fn authentication(&self) -> crate::resources::authentication::AuthenticationResource {
        crate::resources::authentication::AuthenticationResource::new(self.clone())
    }
}
