// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `namespaces` resource.

/// Namespaces
#[derive(Clone)]
pub struct NamespacesResource {
    client: crate::client::Scalar,
}

impl NamespacesResource {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// List namespaces
    pub fn list(&self) -> ListRequestBuilder {
        ListRequestBuilder::new(self.client.clone())
    }
}

/// Get all namespaces for the current team
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRequestBuilder {
    client: crate::client::Scalar,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListRequestBuilder {
    fn new(client: crate::client::Scalar) -> Self {
        Self {
            client,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<String>, crate::error::Error> {
        let path = "/v1/namespaces".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<String>, _>(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
