// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `registry` resource.

#[derive(Clone)]
pub struct Registry {
    client: crate::client::Scalar,
}

impl Registry {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// List all API Documents
    pub fn list_all_api_documents(&self) -> ListAllApiDocumentsRequest {
        ListAllApiDocumentsRequest::new(self.client.clone())
    }

    /// List API Documents in a namespace
    pub fn list_api_documents(&self, namespace: impl Into<String>) -> ListApiDocumentsRequest {
        ListApiDocumentsRequest::new(self.client.clone(), namespace.into())
    }

    /// Create API Document
    pub fn create_api_document(
        &self,
        namespace: impl Into<String>,
        body: crate::models::RegistryCreateApiDocumentBody,
    ) -> CreateApiDocumentRequest {
        CreateApiDocumentRequest::new(self.client.clone(), namespace.into(), body)
    }

    /// Update API Document metadata
    pub fn update_api_document(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        body: crate::models::RegistryUpdateApiDocumentBody,
    ) -> UpdateApiDocumentRequest {
        UpdateApiDocumentRequest::new(self.client.clone(), namespace.into(), slug.into(), body)
    }

    /// Delete API Document
    pub fn delete_api_document(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
    ) -> DeleteApiDocumentRequest {
        DeleteApiDocumentRequest::new(self.client.clone(), namespace.into(), slug.into())
    }

    /// Get API Document
    pub fn retrieve_api_document_version(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        semver: impl Into<String>,
    ) -> RetrieveApiDocumentVersionRequest {
        RetrieveApiDocumentVersionRequest::new(self.client.clone(), namespace.into(), slug.into(), semver.into())
    }

    /// Update API Document version
    pub fn update_api_document_version(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        semver: impl Into<String>,
        body: crate::models::RegistryUpdateApiDocumentVersionBody,
    ) -> UpdateApiDocumentVersionRequest {
        UpdateApiDocumentVersionRequest::new(self.client.clone(), namespace.into(), slug.into(), semver.into(), body)
    }

    /// Delete API Document version
    pub fn delete_api_document_version(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        semver: impl Into<String>,
    ) -> DeleteApiDocumentVersionRequest {
        DeleteApiDocumentVersionRequest::new(self.client.clone(), namespace.into(), slug.into(), semver.into())
    }

    /// Get API Document version metadata
    pub fn list_api_document_version_metadata(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        semver: impl Into<String>,
    ) -> ListApiDocumentVersionMetadataRequest {
        ListApiDocumentVersionMetadataRequest::new(self.client.clone(), namespace.into(), slug.into(), semver.into())
    }

    /// Create API Document version
    pub fn create_api_document_version(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        body: crate::models::RegistryCreateApiDocumentVersionBody,
    ) -> CreateApiDocumentVersionRequest {
        CreateApiDocumentVersionRequest::new(self.client.clone(), namespace.into(), slug.into(), body)
    }

    /// Add access group
    pub fn create_api_document_access_group(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        body: crate::models::AccessGroup,
    ) -> CreateApiDocumentAccessGroupRequest {
        CreateApiDocumentAccessGroupRequest::new(self.client.clone(), namespace.into(), slug.into(), body)
    }

    /// Remove access group
    pub fn delete_api_document_access_group(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        body: crate::models::AccessGroup,
    ) -> DeleteApiDocumentAccessGroupRequest {
        DeleteApiDocumentAccessGroupRequest::new(self.client.clone(), namespace.into(), slug.into(), body)
    }
}

/// List all API documents across every namespace the caller can access.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListAllApiDocumentsRequest {
    client: crate::client::Scalar,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListAllApiDocumentsRequest {
    fn new(client: crate::client::Scalar) -> Self {
        Self {
            client,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::ApiDocument>, crate::error::Error> {
        let path = "/v1/apis".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::ApiDocument>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// List API documents in a namespace.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListApiDocumentsRequest {
    client: crate::client::Scalar,
    namespace: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListApiDocumentsRequest {
    fn new(client: crate::client::Scalar, namespace: String) -> Self {
        Self {
            client,
            namespace,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::ApiDocument>, crate::error::Error> {
        let path = format!("/v1/apis/{}", crate::http::encode_path_param(&self.namespace));
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::ApiDocument>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Create an API document.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateApiDocumentRequest {
    client: crate::client::Scalar,
    namespace: String,
    body: crate::models::RegistryCreateApiDocumentBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateApiDocumentRequest {
    fn new(
        client: crate::client::Scalar,
        namespace: String,
        body: crate::models::RegistryCreateApiDocumentBody,
    ) -> Self {
        Self {
            client,
            namespace,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::RegistryCreateApiDocumentResponse, crate::error::Error> {
        let path = format!("/v1/apis/{}", crate::http::encode_path_param(&self.namespace));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::RegistryCreateApiDocumentResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Update metadata for an API document.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateApiDocumentRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::RegistryUpdateApiDocumentBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdateApiDocumentRequest {
    fn new(
        client: crate::client::Scalar,
        namespace: String,
        slug: String,
        body: crate::models::RegistryUpdateApiDocumentBody,
    ) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::PATCH, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Delete an API document and all versions.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteApiDocumentRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteApiDocumentRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Get a specific API document version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveApiDocumentVersionRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    semver: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl RetrieveApiDocumentVersionRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, semver: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            semver,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    pub async fn send(self) -> Result<bytes::Bytes, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/version/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug),
            crate::http::encode_path_param(&self.semver)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        headers.push(("Accept".to_string(), "text/plain".to_string()));
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send_bytes(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Update the registry file content for an API document version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateApiDocumentVersionRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    semver: String,
    body: crate::models::RegistryUpdateApiDocumentVersionBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdateApiDocumentVersionRequest {
    fn new(
        client: crate::client::Scalar,
        namespace: String,
        slug: String,
        semver: String,
        body: crate::models::RegistryUpdateApiDocumentVersionBody,
    ) -> Self {
        Self {
            client,
            namespace,
            slug,
            semver,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::RegistryUpdateApiDocumentVersionResponse, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/version/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug),
            crate::http::encode_path_param(&self.semver)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::RegistryUpdateApiDocumentVersionResponse, _>(
                http::Method::PATCH,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Delete a specific API document version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteApiDocumentVersionRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    semver: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteApiDocumentVersionRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, semver: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            semver,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/version/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug),
            crate::http::encode_path_param(&self.semver)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Get metadata (uid, content shas, version sha, tags) for a specific API document version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListApiDocumentVersionMetadataRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    semver: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListApiDocumentVersionMetadataRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, semver: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            semver,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ManagedDocVersion, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/version/{}/metadata",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug),
            crate::http::encode_path_param(&self.semver)
        );
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ManagedDocVersion, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Create a new API document version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateApiDocumentVersionRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::RegistryCreateApiDocumentVersionBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateApiDocumentVersionRequest {
    fn new(
        client: crate::client::Scalar,
        namespace: String,
        slug: String,
        body: crate::models::RegistryCreateApiDocumentVersionBody,
    ) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ManagedDocVersion, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/version",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ManagedDocVersion, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Add an access group to an API document.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateApiDocumentAccessGroupRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::AccessGroup,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateApiDocumentAccessGroupRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, body: crate::models::AccessGroup) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/access-group",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Remove an access group from an API document.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteApiDocumentAccessGroupRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::AccessGroup,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteApiDocumentAccessGroupRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, body: crate::models::AccessGroup) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/access-group",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
