// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `registry` resource.

/// Registry
#[derive(Clone)]
pub struct RegistryResource {
    client: crate::client::Scalar,
}

impl RegistryResource {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// List all API Documents
    pub fn list_all_api_documents(&self) -> ListAllApiDocumentsRequestBuilder {
        ListAllApiDocumentsRequestBuilder::new(self.client.clone())
    }

    /// List API Documents in a namespace
    pub fn list_api_documents(&self, namespace: impl Into<String>) -> ListApiDocumentsRequestBuilder {
        ListApiDocumentsRequestBuilder::new(self.client.clone(), namespace.into())
    }

    /// Create API Document
    pub fn create_api_document(
        &self,
        namespace: impl Into<String>,
        body: crate::models::RegistryCreateApiDocumentBody,
    ) -> CreateApiDocumentRequestBuilder {
        CreateApiDocumentRequestBuilder::new(self.client.clone(), namespace.into(), body)
    }

    /// Update API Document metadata
    pub fn update_api_document(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        body: crate::models::RegistryUpdateApiDocumentBody,
    ) -> UpdateApiDocumentRequestBuilder {
        UpdateApiDocumentRequestBuilder::new(self.client.clone(), namespace.into(), slug.into(), body)
    }

    /// Delete API Document
    pub fn delete_api_document(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
    ) -> DeleteApiDocumentRequestBuilder {
        DeleteApiDocumentRequestBuilder::new(self.client.clone(), namespace.into(), slug.into())
    }

    /// Get API Document
    pub fn retrieve_api_document_version(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        semver: impl Into<String>,
    ) -> RetrieveApiDocumentVersionRequestBuilder {
        RetrieveApiDocumentVersionRequestBuilder::new(self.client.clone(), namespace.into(), slug.into(), semver.into())
    }

    /// Update API Document version
    pub fn update_api_document_version(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        semver: impl Into<String>,
        body: crate::models::RegistryUpdateApiDocumentVersionBody,
    ) -> UpdateApiDocumentVersionRequestBuilder {
        UpdateApiDocumentVersionRequestBuilder::new(
            self.client.clone(),
            namespace.into(),
            slug.into(),
            semver.into(),
            body,
        )
    }

    /// Delete API Document version
    pub fn delete_api_document_version(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        semver: impl Into<String>,
    ) -> DeleteApiDocumentVersionRequestBuilder {
        DeleteApiDocumentVersionRequestBuilder::new(self.client.clone(), namespace.into(), slug.into(), semver.into())
    }

    /// Get API Document version metadata
    pub fn list_api_document_version_metadata(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        semver: impl Into<String>,
    ) -> ListApiDocumentVersionMetadataRequestBuilder {
        ListApiDocumentVersionMetadataRequestBuilder::new(
            self.client.clone(),
            namespace.into(),
            slug.into(),
            semver.into(),
        )
    }

    /// Create API Document version
    pub fn create_api_document_version(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        body: crate::models::RegistryCreateApiDocumentVersionBody,
    ) -> CreateApiDocumentVersionRequestBuilder {
        CreateApiDocumentVersionRequestBuilder::new(self.client.clone(), namespace.into(), slug.into(), body)
    }

    /// Add access group
    pub fn create_api_document_access_group(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        body: crate::models::AccessGroup,
    ) -> CreateApiDocumentAccessGroupRequestBuilder {
        CreateApiDocumentAccessGroupRequestBuilder::new(self.client.clone(), namespace.into(), slug.into(), body)
    }

    /// Remove access group
    pub fn delete_api_document_access_group(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        body: crate::models::AccessGroup,
    ) -> DeleteApiDocumentAccessGroupRequestBuilder {
        DeleteApiDocumentAccessGroupRequestBuilder::new(self.client.clone(), namespace.into(), slug.into(), body)
    }
}

/// List all API documents across every namespace the caller can access.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListAllApiDocumentsRequestBuilder {
    client: crate::client::Scalar,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListAllApiDocumentsRequestBuilder {
    fn new(client: crate::client::Scalar) -> Self {
        Self {
            client,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::ApiDocument>, crate::error::Error> {
        let path = "/v1/apis".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::ApiDocument>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// List API documents in a namespace.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListApiDocumentsRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListApiDocumentsRequestBuilder {
    fn new(client: crate::client::Scalar, namespace: String) -> Self {
        Self {
            client,
            namespace,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::ApiDocument>, crate::error::Error> {
        let path = format!("/v1/apis/{}", crate::http::encode_path_param(&self.namespace));
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::ApiDocument>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Create an API document.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateApiDocumentRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    body: crate::models::RegistryCreateApiDocumentBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateApiDocumentRequestBuilder {
    fn new(
        client: crate::client::Scalar,
        namespace: String,
        body: crate::models::RegistryCreateApiDocumentBody,
    ) -> Self {
        Self {
            client,
            namespace,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::RegistryCreateApiDocumentResponse, crate::error::Error> {
        let path = format!("/v1/apis/{}", crate::http::encode_path_param(&self.namespace));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::RegistryCreateApiDocumentResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Update metadata for an API document.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateApiDocumentRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::RegistryUpdateApiDocumentBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdateApiDocumentRequestBuilder {
    fn new(
        client: crate::client::Scalar,
        namespace: String,
        slug: String,
        body: crate::models::RegistryUpdateApiDocumentBody,
    ) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::PATCH, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Delete an API document and all versions.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteApiDocumentRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteApiDocumentRequestBuilder {
    fn new(client: crate::client::Scalar, namespace: String, slug: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Get a specific API document version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveApiDocumentVersionRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    semver: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl RetrieveApiDocumentVersionRequestBuilder {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, semver: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            semver,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    pub async fn send(self) -> Result<bytes::Bytes, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/version/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug),
            crate::http::encode_path_param(&self.semver)
        );
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = vec![("Accept".to_string(), "text/plain".to_string())];
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send_bytes(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Update the registry file content for an API document version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateApiDocumentVersionRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    semver: String,
    body: crate::models::RegistryUpdateApiDocumentVersionBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdateApiDocumentVersionRequestBuilder {
    fn new(
        client: crate::client::Scalar,
        namespace: String,
        slug: String,
        semver: String,
        body: crate::models::RegistryUpdateApiDocumentVersionBody,
    ) -> Self {
        Self {
            client,
            namespace,
            slug,
            semver,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::RegistryUpdateApiDocumentVersionResponse, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/version/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug),
            crate::http::encode_path_param(&self.semver)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::RegistryUpdateApiDocumentVersionResponse, _>(
                http::Method::PATCH,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Delete a specific API document version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteApiDocumentVersionRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    semver: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteApiDocumentVersionRequestBuilder {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, semver: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            semver,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/version/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug),
            crate::http::encode_path_param(&self.semver)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Get metadata (uid, content shas, version sha, tags) for a specific API document version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListApiDocumentVersionMetadataRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    semver: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListApiDocumentVersionMetadataRequestBuilder {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, semver: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            semver,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ManagedDocVersion, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/version/{}/metadata",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug),
            crate::http::encode_path_param(&self.semver)
        );
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ManagedDocVersion, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Create a new API document version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateApiDocumentVersionRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::RegistryCreateApiDocumentVersionBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateApiDocumentVersionRequestBuilder {
    fn new(
        client: crate::client::Scalar,
        namespace: String,
        slug: String,
        body: crate::models::RegistryCreateApiDocumentVersionBody,
    ) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ManagedDocVersion, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/version",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ManagedDocVersion, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Add an access group to an API document.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateApiDocumentAccessGroupRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::AccessGroup,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateApiDocumentAccessGroupRequestBuilder {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, body: crate::models::AccessGroup) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/access-group",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Remove an access group from an API document.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteApiDocumentAccessGroupRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::AccessGroup,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteApiDocumentAccessGroupRequestBuilder {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, body: crate::models::AccessGroup) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/apis/{}/{}/access-group",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
