// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `repositories` resource.

/// SDKs
#[derive(Clone)]
pub struct RepositoriesResource {
    client: crate::client::Scalar,
}

impl RepositoriesResource {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// Link a repository
    pub fn link(&self, uid: impl Into<String>, body: crate::models::RepositoriesLinkBody) -> LinkRequestBuilder {
        LinkRequestBuilder::new(self.client.clone(), uid.into(), body)
    }

    /// Unlink a repository
    pub fn unlink(&self, uid: impl Into<String>, language: impl Into<String>) -> UnlinkRequestBuilder {
        UnlinkRequestBuilder::new(self.client.clone(), uid.into(), language.into())
    }

    /// Update publishing settings
    pub fn update_publishing(
        &self,
        uid: impl Into<String>,
        language: impl Into<String>,
        body: crate::models::RepositoriesUpdatePublishingBody,
    ) -> UpdatePublishingRequestBuilder {
        UpdatePublishingRequestBuilder::new(self.client.clone(), uid.into(), language.into(), body)
    }
}

/// Link one language target to a GitHub repository, so builds sync there.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct LinkRequestBuilder {
    client: crate::client::Scalar,
    uid: String,
    body: crate::models::RepositoriesLinkBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl LinkRequestBuilder {
    fn new(client: crate::client::Scalar, uid: String, body: crate::models::RepositoriesLinkBody) -> Self {
        Self {
            client,
            uid,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Option<crate::models::RepositoriesLinkResponse>, crate::error::Error> {
        let path = format!("/v1/sdks/{}/repositories", crate::http::encode_path_param(&self.uid));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Option<crate::models::RepositoriesLinkResponse>, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Unlink one language target from its repository.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UnlinkRequestBuilder {
    client: crate::client::Scalar,
    uid: String,
    language: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UnlinkRequestBuilder {
    fn new(client: crate::client::Scalar, uid: String, language: String) -> Self {
        Self {
            client,
            uid,
            language,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/sdks/{}/repositories/{}",
            crate::http::encode_path_param(&self.uid),
            crate::http::encode_path_param(&self.language)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Toggle publish-on-merge and the release settings for a linked target.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdatePublishingRequestBuilder {
    client: crate::client::Scalar,
    uid: String,
    language: String,
    body: crate::models::RepositoriesUpdatePublishingBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdatePublishingRequestBuilder {
    fn new(
        client: crate::client::Scalar,
        uid: String,
        language: String,
        body: crate::models::RepositoriesUpdatePublishingBody,
    ) -> Self {
        Self {
            client,
            uid,
            language,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/sdks/{}/repositories/{}/publishing",
            crate::http::encode_path_param(&self.uid),
            crate::http::encode_path_param(&self.language)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await
    }
}
