// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `rules` resource.

#[derive(Clone)]
pub struct Rules {
    client: crate::client::Scalar,
}

impl Rules {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// List all rules
    pub fn list_rulesets(&self, namespace: impl Into<String>) -> ListRulesetsRequest {
        ListRulesetsRequest::new(self.client.clone(), namespace.into())
    }

    /// Create a rule
    pub fn create_ruleset(&self, namespace: impl Into<String>, body: crate::models::RulesCreateRulesetBody) -> CreateRulesetRequest {
        CreateRulesetRequest::new(self.client.clone(), namespace.into(), body)
    }

    /// Update rule metadata
    pub fn update_ruleset(&self, namespace: impl Into<String>, slug: impl Into<String>, body: crate::models::RulesUpdateRulesetBody) -> UpdateRulesetRequest {
        UpdateRulesetRequest::new(self.client.clone(), namespace.into(), slug.into(), body)
    }

    /// Delete a rule
    pub fn delete_ruleset(&self, namespace: impl Into<String>, slug: impl Into<String>) -> DeleteRulesetRequest {
        DeleteRulesetRequest::new(self.client.clone(), namespace.into(), slug.into())
    }

    /// Get a rule
    pub fn retrieve_ruleset_document(&self, namespace: impl Into<String>, slug: impl Into<String>) -> RetrieveRulesetDocumentRequest {
        RetrieveRulesetDocumentRequest::new(self.client.clone(), namespace.into(), slug.into())
    }

    /// Add rule access group
    pub fn create_ruleset_access_group(&self, namespace: impl Into<String>, slug: impl Into<String>, body: crate::models::AccessGroup) -> CreateRulesetAccessGroupRequest {
        CreateRulesetAccessGroupRequest::new(self.client.clone(), namespace.into(), slug.into(), body)
    }

    /// Remove rule access group
    pub fn delete_ruleset_access_group(&self, namespace: impl Into<String>, slug: impl Into<String>, body: crate::models::AccessGroup) -> DeleteRulesetAccessGroupRequest {
        DeleteRulesetAccessGroupRequest::new(self.client.clone(), namespace.into(), slug.into(), body)
    }
}

/// List all rulesets in a namespace.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRulesetsRequest {
    client: crate::client::Scalar,
    namespace: String,
}

impl ListRulesetsRequest {
    fn new(client: crate::client::Scalar, namespace: String) -> Self {
        Self {
            client,
            namespace,
        }
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<Vec<crate::models::Rule>, crate::error::Error> {
        let path = format!("/v1/rulesets/{}", crate::http::encode_path_param(&self.namespace));
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<Vec<crate::models::Rule>, _>(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
/// Create a rule in a namespace.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRulesetRequest {
    client: crate::client::Scalar,
    namespace: String,
    body: crate::models::RulesCreateRulesetBody,
    idempotency_key: Option<String>,
}

impl CreateRulesetRequest {
    fn new(client: crate::client::Scalar, namespace: String, body: crate::models::RulesCreateRulesetBody) -> Self {
        Self {
            client,
            namespace,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::Uid, crate::error::Error> {
        let path = format!("/v1/rulesets/{}", crate::http::encode_path_param(&self.namespace));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<crate::models::Uid, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
/// Update rule metadata by slug.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateRulesetRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::RulesUpdateRulesetBody,
    idempotency_key: Option<String>,
}

impl UpdateRulesetRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, body: crate::models::RulesUpdateRulesetBody) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/rulesets/{}/{}", crate::http::encode_path_param(&self.namespace), crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<serde_json::Value, _>(reqwest::Method::PATCH, &path, &query, &headers, body, true)
            .await
    }
}
/// Delete a rule by slug.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteRulesetRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    idempotency_key: Option<String>,
}

impl DeleteRulesetRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/rulesets/{}/{}", crate::http::encode_path_param(&self.namespace), crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<serde_json::Value, _>(reqwest::Method::DELETE, &path, &query, &headers, body, true)
            .await
    }
}
/// Get a rule document by slug.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveRulesetDocumentRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
}

impl RetrieveRulesetDocumentRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String) -> Self {
        Self {
            client,
            namespace,
            slug,
        }
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<bytes::Bytes, crate::error::Error> {
        let path = format!("/v1/rulesets/{}/{}", crate::http::encode_path_param(&self.namespace), crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send_bytes(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
/// Grant an access group to a rule.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRulesetAccessGroupRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::AccessGroup,
    idempotency_key: Option<String>,
}

impl CreateRulesetAccessGroupRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, body: crate::models::AccessGroup) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/rulesets/{}/{}/access-group", crate::http::encode_path_param(&self.namespace), crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<serde_json::Value, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
/// Remove an access group from a rule.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteRulesetAccessGroupRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::AccessGroup,
    idempotency_key: Option<String>,
}

impl DeleteRulesetAccessGroupRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, body: crate::models::AccessGroup) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/rulesets/{}/{}/access-group", crate::http::encode_path_param(&self.namespace), crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<serde_json::Value, _>(reqwest::Method::DELETE, &path, &query, &headers, body, true)
            .await
    }
}
