// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `scalarDocs` resource.

/// Scalar Docs
#[derive(Clone)]
pub struct ScalarDocsResource {
    client: crate::client::Scalar,
}

impl ScalarDocsResource {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// List all projects
    pub fn list_guides(&self) -> ListGuidesRequestBuilder {
        ListGuidesRequestBuilder::new(self.client.clone())
    }

    /// Create a project
    pub fn create_guide(&self, body: crate::models::ScalarDocsCreateGuideBody) -> CreateGuideRequestBuilder {
        CreateGuideRequestBuilder::new(self.client.clone(), body)
    }

    /// Publish a project
    pub fn publish_guide(&self, slug: impl Into<String>) -> PublishGuideRequestBuilder {
        PublishGuideRequestBuilder::new(self.client.clone(), slug.into())
    }
}

/// List all guide projects.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListGuidesRequestBuilder {
    client: crate::client::Scalar,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListGuidesRequestBuilder {
    fn new(client: crate::client::Scalar) -> Self {
        Self {
            client,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::GithubProject>, crate::error::Error> {
        let path = "/v1/guides".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::GithubProject>, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Create a guide project.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateGuideRequestBuilder {
    client: crate::client::Scalar,
    body: crate::models::ScalarDocsCreateGuideBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateGuideRequestBuilder {
    fn new(client: crate::client::Scalar, body: crate::models::ScalarDocsCreateGuideBody) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ScalarDocsCreateGuideResponse, crate::error::Error> {
        let path = "/v1/guides".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ScalarDocsCreateGuideResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Start a new publish process.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct PublishGuideRequestBuilder {
    client: crate::client::Scalar,
    slug: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl PublishGuideRequestBuilder {
    fn new(client: crate::client::Scalar, slug: String) -> Self {
        Self {
            client,
            slug,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::ScalarDocsPublishGuideResponse, crate::error::Error> {
        let path = format!("/v1/guides/{}/publish", crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::ScalarDocsPublishGuideResponse, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
