// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `scalarDocs` resource.

#[derive(Clone)]
pub struct ScalarDocs {
    client: crate::client::Scalar,
}

impl ScalarDocs {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// List all projects
    pub fn list_guides(&self) -> ListGuidesRequest {
        ListGuidesRequest::new(self.client.clone())
    }

    /// Create a project
    pub fn create_guide(&self, body: crate::models::ScalarDocsCreateGuideBody) -> CreateGuideRequest {
        CreateGuideRequest::new(self.client.clone(), body)
    }

    /// Publish a project
    pub fn publish_guide(&self, slug: impl Into<String>) -> PublishGuideRequest {
        PublishGuideRequest::new(self.client.clone(), slug.into())
    }
}

/// List all guide projects.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListGuidesRequest {
    client: crate::client::Scalar,
}

impl ListGuidesRequest {
    fn new(client: crate::client::Scalar) -> Self {
        Self {
            client,
        }
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<Vec<crate::models::GithubProject>, crate::error::Error> {
        let path = "/v1/guides".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<Vec<crate::models::GithubProject>, _>(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
/// Create a guide project.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateGuideRequest {
    client: crate::client::Scalar,
    body: crate::models::ScalarDocsCreateGuideBody,
    idempotency_key: Option<String>,
}

impl CreateGuideRequest {
    fn new(client: crate::client::Scalar, body: crate::models::ScalarDocsCreateGuideBody) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::ScalarDocsCreateGuideResponse, crate::error::Error> {
        let path = "/v1/guides".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<crate::models::ScalarDocsCreateGuideResponse, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
/// Start a new publish process.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct PublishGuideRequest {
    client: crate::client::Scalar,
    slug: String,
    idempotency_key: Option<String>,
}

impl PublishGuideRequest {
    fn new(client: crate::client::Scalar, slug: String) -> Self {
        Self {
            client,
            slug,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::ScalarDocsPublishGuideResponse, crate::error::Error> {
        let path = format!("/v1/guides/{}/publish", crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<crate::models::ScalarDocsPublishGuideResponse, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
