// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `schemas` resource.

#[derive(Clone)]
pub struct Schemas {
    client: crate::client::Scalar,
}

impl Schemas {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// List all shared components
    pub fn list(&self, namespace: impl Into<String>) -> ListRequest {
        ListRequest::new(self.client.clone(), namespace.into())
    }

    /// Create a shared component
    pub fn create(&self, namespace: impl Into<String>, body: crate::models::SchemasCreateBody) -> CreateRequest {
        CreateRequest::new(self.client.clone(), namespace.into(), body)
    }

    /// Update shared component metadata
    pub fn update(&self, namespace: impl Into<String>, slug: impl Into<String>, body: crate::models::SchemasUpdateBody) -> UpdateRequest {
        UpdateRequest::new(self.client.clone(), namespace.into(), slug.into(), body)
    }

    /// Delete a shared component
    pub fn delete(&self, namespace: impl Into<String>, slug: impl Into<String>) -> DeleteRequest {
        DeleteRequest::new(self.client.clone(), namespace.into(), slug.into())
    }

    pub fn version(&self) -> crate::resources::version::Version {
        crate::resources::version::Version::new(self.client.clone())
    }

    pub fn access_group(&self) -> crate::resources::access_group::AccessGroup {
        crate::resources::access_group::AccessGroup::new(self.client.clone())
    }
}

/// List schemas in a namespace.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRequest {
    client: crate::client::Scalar,
    namespace: String,
}

impl ListRequest {
    fn new(client: crate::client::Scalar, namespace: String) -> Self {
        Self {
            client,
            namespace,
        }
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<Vec<crate::models::Schema>, crate::error::Error> {
        let path = format!("/v1/schemas/{}", crate::http::encode_path_param(&self.namespace));
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<Vec<crate::models::Schema>, _>(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
/// Create a schema in a namespace.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRequest {
    client: crate::client::Scalar,
    namespace: String,
    body: crate::models::SchemasCreateBody,
    idempotency_key: Option<String>,
}

impl CreateRequest {
    fn new(client: crate::client::Scalar, namespace: String, body: crate::models::SchemasCreateBody) -> Self {
        Self {
            client,
            namespace,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::Uid, crate::error::Error> {
        let path = format!("/v1/schemas/{}", crate::http::encode_path_param(&self.namespace));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<crate::models::Uid, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
/// Update schema metadata.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::SchemasUpdateBody,
    idempotency_key: Option<String>,
}

impl UpdateRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, body: crate::models::SchemasUpdateBody) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/schemas/{}/{}", crate::http::encode_path_param(&self.namespace), crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<serde_json::Value, _>(reqwest::Method::PATCH, &path, &query, &headers, body, true)
            .await
    }
}
/// Delete a schema and all related versions.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    idempotency_key: Option<String>,
}

impl DeleteRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/schemas/{}/{}", crate::http::encode_path_param(&self.namespace), crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<serde_json::Value, _>(reqwest::Method::DELETE, &path, &query, &headers, body, true)
            .await
    }
}
