// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `schemas` resource.

/// Schemas
#[derive(Clone)]
pub struct SchemasResource {
    client: crate::client::Scalar,
}

impl SchemasResource {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// List all shared components
    pub fn list(&self, namespace: impl Into<String>) -> ListRequestBuilder {
        ListRequestBuilder::new(self.client.clone(), namespace.into())
    }

    /// Create a shared component
    pub fn create(&self, namespace: impl Into<String>, body: crate::models::SchemasCreateBody) -> CreateRequestBuilder {
        CreateRequestBuilder::new(self.client.clone(), namespace.into(), body)
    }

    /// Update shared component metadata
    pub fn update(
        &self,
        namespace: impl Into<String>,
        slug: impl Into<String>,
        body: crate::models::SchemasUpdateBody,
    ) -> UpdateRequestBuilder {
        UpdateRequestBuilder::new(self.client.clone(), namespace.into(), slug.into(), body)
    }

    /// Delete a shared component
    pub fn delete(&self, namespace: impl Into<String>, slug: impl Into<String>) -> DeleteRequestBuilder {
        DeleteRequestBuilder::new(self.client.clone(), namespace.into(), slug.into())
    }

    /// Schemas
    pub fn version(&self) -> crate::resources::version::VersionResource {
        crate::resources::version::VersionResource::new(self.client.clone())
    }

    /// Schemas
    pub fn access_group(&self) -> crate::resources::access_group::AccessGroupResource {
        crate::resources::access_group::AccessGroupResource::new(self.client.clone())
    }
}

/// List schemas in a namespace.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListRequestBuilder {
    fn new(client: crate::client::Scalar, namespace: String) -> Self {
        Self {
            client,
            namespace,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::Schema>, crate::error::Error> {
        let path = format!("/v1/schemas/{}", crate::http::encode_path_param(&self.namespace));
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::Schema>, _>(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Create a schema in a namespace.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    body: crate::models::SchemasCreateBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateRequestBuilder {
    fn new(client: crate::client::Scalar, namespace: String, body: crate::models::SchemasCreateBody) -> Self {
        Self {
            client,
            namespace,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::Uid, crate::error::Error> {
        let path = format!("/v1/schemas/{}", crate::http::encode_path_param(&self.namespace));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::Uid, _>(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Update schema metadata.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::SchemasUpdateBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdateRequestBuilder {
    fn new(
        client: crate::client::Scalar,
        namespace: String,
        slug: String,
        body: crate::models::SchemasUpdateBody,
    ) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/schemas/{}/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::PATCH, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Delete a schema and all related versions.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteRequestBuilder {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteRequestBuilder {
    fn new(client: crate::client::Scalar, namespace: String, slug: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!(
            "/v1/schemas/{}/{}",
            crate::http::encode_path_param(&self.namespace),
            crate::http::encode_path_param(&self.slug)
        );
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
