// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `sdks` resource.

/// SDKs
#[derive(Clone)]
pub struct SdksResource {
    client: crate::client::Scalar,
}

impl SdksResource {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// List all SDKs
    pub fn list(&self) -> ListRequestBuilder {
        ListRequestBuilder::new(self.client.clone())
    }

    /// Create an SDK
    pub fn create(&self, body: crate::models::SdksCreateBody) -> CreateRequestBuilder {
        CreateRequestBuilder::new(self.client.clone(), body)
    }

    /// Get an SDK
    pub fn retrieve(&self, uid: impl Into<String>) -> RetrieveRequestBuilder {
        RetrieveRequestBuilder::new(self.client.clone(), uid.into())
    }

    /// Update an SDK
    pub fn update(&self, uid: impl Into<String>, body: crate::models::SdksUpdateBody) -> UpdateRequestBuilder {
        UpdateRequestBuilder::new(self.client.clone(), uid.into(), body)
    }

    /// Delete an SDK
    pub fn delete(&self, uid: impl Into<String>) -> DeleteRequestBuilder {
        DeleteRequestBuilder::new(self.client.clone(), uid.into())
    }

    /// Build an SDK
    pub fn build(&self, uid: impl Into<String>, body: crate::models::SdksBuildBody) -> BuildRequestBuilder {
        BuildRequestBuilder::new(self.client.clone(), uid.into(), body)
    }

    /// SDKs
    pub fn versions(&self) -> crate::resources::versions::VersionsResource {
        crate::resources::versions::VersionsResource::new(self.client.clone())
    }

    /// SDKs
    pub fn repositories(&self) -> crate::resources::repositories::RepositoriesResource {
        crate::resources::repositories::RepositoriesResource::new(self.client.clone())
    }
}

/// List every SDK on the team.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRequestBuilder {
    client: crate::client::Scalar,
    limit: Option<i64>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListRequestBuilder {
    fn new(client: crate::client::Scalar) -> Self {
        Self {
            client,
            limit: None,
            timeout: None,
            max_retries: None,
        }
    }

    pub fn limit(mut self, value: i64) -> Self {
        self.limit = Some(value);
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::SdksListResponse, crate::error::Error> {
        let path = "/v1/sdks".to_string();
        let mut query: Vec<(String, String)> = Vec::new();
        if let Some(value) = &self.limit {
            query.push(("limit".to_string(), crate::http::scalar_value(value)));
        }
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::SdksListResponse, _>(
                http::Method::GET,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
/// Create an SDK from an API document, targeting one or more languages.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRequestBuilder {
    client: crate::client::Scalar,
    body: crate::models::SdksCreateBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateRequestBuilder {
    fn new(client: crate::client::Scalar, body: crate::models::SdksCreateBody) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::Uid, crate::error::Error> {
        let path = "/v1/sdks".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::Uid, _>(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Get a single SDK by its uid.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveRequestBuilder {
    client: crate::client::Scalar,
    uid: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl RetrieveRequestBuilder {
    fn new(client: crate::client::Scalar, uid: String) -> Self {
        Self {
            client,
            uid,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::Sdk, crate::error::Error> {
        let path = format!("/v1/sdks/{}", crate::http::encode_path_param(&self.uid));
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::Sdk, _>(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Update SDK metadata, its linked API, or its config.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateRequestBuilder {
    client: crate::client::Scalar,
    uid: String,
    body: crate::models::SdksUpdateBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdateRequestBuilder {
    fn new(client: crate::client::Scalar, uid: String, body: crate::models::SdksUpdateBody) -> Self {
        Self {
            client,
            uid,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/sdks/{}", crate::http::encode_path_param(&self.uid));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::PATCH, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Delete an SDK and every version it holds.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteRequestBuilder {
    client: crate::client::Scalar,
    uid: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteRequestBuilder {
    fn new(client: crate::client::Scalar, uid: String) -> Self {
        Self {
            client,
            uid,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/sdks/{}", crate::http::encode_path_param(&self.uid));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Start a build. Omit `version` to build the current work — the open draft, else the latest version — and the resolved version comes back in the response.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct BuildRequestBuilder {
    client: crate::client::Scalar,
    uid: String,
    body: crate::models::SdksBuildBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl BuildRequestBuilder {
    fn new(client: crate::client::Scalar, uid: String, body: crate::models::SdksBuildBody) -> Self {
        Self {
            client,
            uid,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline for this request only.
    /// It bounds each attempt up to response headers, then the buffered
    /// body read, so total wall time can exceed the value set here. A
    /// streamed body is never deadline-killed; see `ClientBuilder::timeout`.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Option<crate::models::SdksBuildResponse>, crate::error::Error> {
        let path = format!("/v1/sdks/{}/build", crate::http::encode_path_param(&self.uid));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Option<crate::models::SdksBuildResponse>, _>(
                http::Method::POST,
                &path,
                &query,
                &headers,
                body,
                true,
                overrides,
            )
            .await
    }
}
