// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `themes` resource.

#[derive(Clone)]
pub struct Themes {
    client: crate::client::Scalar,
}

impl Themes {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// List all themes
    pub fn list(&self) -> ListRequest {
        ListRequest::new(self.client.clone())
    }

    /// Create a theme
    pub fn create(&self, body: crate::models::ThemesCreateBody) -> CreateRequest {
        CreateRequest::new(self.client.clone(), body)
    }

    /// Update theme metadata
    pub fn update(&self, slug: impl Into<String>, body: crate::models::ThemesUpdateBody) -> UpdateRequest {
        UpdateRequest::new(self.client.clone(), slug.into(), body)
    }

    /// Update theme document
    pub fn replace_document(
        &self,
        slug: impl Into<String>,
        body: crate::models::ThemesReplaceDocumentBody,
    ) -> ReplaceDocumentRequest {
        ReplaceDocumentRequest::new(self.client.clone(), slug.into(), body)
    }

    /// Delete a theme
    pub fn delete(&self, slug: impl Into<String>) -> DeleteRequest {
        DeleteRequest::new(self.client.clone(), slug.into())
    }

    /// Get a theme
    pub fn retrieve(&self, slug: impl Into<String>) -> RetrieveRequest {
        RetrieveRequest::new(self.client.clone(), slug.into())
    }
}

/// List all team themes.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ListRequest {
    client: crate::client::Scalar,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ListRequest {
    fn new(client: crate::client::Scalar) -> Self {
        Self {
            client,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<Vec<crate::models::Theme>, crate::error::Error> {
        let path = "/v1/themes".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<Vec<crate::models::Theme>, _>(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Create a team theme.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateRequest {
    client: crate::client::Scalar,
    body: crate::models::ThemesCreateBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl CreateRequest {
    fn new(client: crate::client::Scalar, body: crate::models::ThemesCreateBody) -> Self {
        Self {
            client,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<crate::models::Uid, crate::error::Error> {
        let path = "/v1/themes".to_string();
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<crate::models::Uid, _>(http::Method::POST, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Update theme metadata.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct UpdateRequest {
    client: crate::client::Scalar,
    slug: String,
    body: crate::models::ThemesUpdateBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl UpdateRequest {
    fn new(client: crate::client::Scalar, slug: String, body: crate::models::ThemesUpdateBody) -> Self {
        Self {
            client,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/themes/{}", crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::PATCH, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Replace the theme document.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct ReplaceDocumentRequest {
    client: crate::client::Scalar,
    slug: String,
    body: crate::models::ThemesReplaceDocumentBody,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl ReplaceDocumentRequest {
    fn new(client: crate::client::Scalar, slug: String, body: crate::models::ThemesReplaceDocumentBody) -> Self {
        Self {
            client,
            slug,
            body,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/themes/{}", crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::PUT, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Delete a theme by slug.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteRequest {
    client: crate::client::Scalar,
    slug: String,
    idempotency_key: Option<String>,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl DeleteRequest {
    fn new(client: crate::client::Scalar, slug: String) -> Self {
        Self {
            client,
            slug,
            idempotency_key: None,
            timeout: None,
            max_retries: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    /// - [`Error::Serde`](crate::error::Error::Serde) — the response body did not
    ///   match the generated model.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/themes/{}", crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send::<serde_json::Value, _>(http::Method::DELETE, &path, &query, &headers, body, true, overrides)
            .await
    }
}
/// Get the theme document by slug.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveRequest {
    client: crate::client::Scalar,
    slug: String,
    timeout: Option<std::time::Duration>,
    max_retries: Option<u32>,
}

impl RetrieveRequest {
    fn new(client: crate::client::Scalar, slug: String) -> Self {
        Self {
            client,
            slug,
            timeout: None,
            max_retries: None,
        }
    }

    /// Overrides the client's request deadline (connection setup +
    /// time-to-response-headers) for this request only. The bound is
    /// **per attempt** — each retry gets a fresh deadline — so with
    /// retries enabled total wall time can exceed the value set here.
    pub fn timeout(mut self, timeout: std::time::Duration) -> Self {
        self.timeout = Some(timeout);
        self
    }

    /// Overrides the client's maximum retry attempts for this request only.
    pub fn max_retries(mut self, max_retries: u32) -> Self {
        self.max_retries = Some(max_retries);
        self
    }

    /// Sends the request and returns the decoded response.
    ///
    /// # Errors
    ///
    /// - [`Error::Api`](crate::error::Error::Api) — the server answered with a
    ///   non-success status; the status, headers, request id, and decoded body are
    ///   preserved on the [`ApiError`](crate::error::ApiError).
    /// - [`Error::Transport`](crate::error::Error::Transport) — the request never
    ///   produced a response (connection failure, or the deadline elapsed).
    /// - [`Error::Config`](crate::error::Error::Config) — a parameter value could not
    ///   be rendered into the request.
    pub async fn send(self) -> Result<bytes::Bytes, crate::error::Error> {
        let path = format!("/v1/themes/{}", crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        headers.push(("Accept".to_string(), "text/plain".to_string()));
        let body: Option<&serde_json::Value> = None;
        let overrides = crate::client::RequestOverrides {
            timeout: self.timeout,
            max_retries: self.max_retries,
        };
        self.client
            .send_bytes(http::Method::GET, &path, &query, &headers, body, true, overrides)
            .await
    }
}
