// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! The `version` resource.

#[derive(Clone)]
pub struct Version {
    client: crate::client::Scalar,
}

impl Version {
    pub(crate) fn new(client: crate::client::Scalar) -> Self {
        Self { client }
    }

    /// Get a shared component document
    pub fn retrieve_schema(&self, namespace: impl Into<String>, slug: impl Into<String>, semver: impl Into<String>) -> RetrieveSchemaRequest {
        RetrieveSchemaRequest::new(self.client.clone(), namespace.into(), slug.into(), semver.into())
    }

    /// Delete a shared component version
    pub fn delete_schema(&self, namespace: impl Into<String>, slug: impl Into<String>, semver: impl Into<String>) -> DeleteSchemaRequest {
        DeleteSchemaRequest::new(self.client.clone(), namespace.into(), slug.into(), semver.into())
    }

    /// Create a shared component version
    pub fn create_schema(&self, namespace: impl Into<String>, slug: impl Into<String>, body: crate::models::VersionCreateSchemaBody) -> CreateSchemaRequest {
        CreateSchemaRequest::new(self.client.clone(), namespace.into(), slug.into(), body)
    }
}

/// Get a specific schema version document.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct RetrieveSchemaRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    semver: String,
}

impl RetrieveSchemaRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, semver: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            semver,
        }
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<bytes::Bytes, crate::error::Error> {
        let path = format!("/v1/schemas/{}/{}/version/{}", crate::http::encode_path_param(&self.namespace), crate::http::encode_path_param(&self.slug), crate::http::encode_path_param(&self.semver));
        let query: Vec<(String, String)> = Vec::new();
        let headers: Vec<(String, String)> = Vec::new();
        let body: Option<&serde_json::Value> = None;
        self.client
            .send_bytes(reqwest::Method::GET, &path, &query, &headers, body, true)
            .await
    }
}
/// Delete a schema version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct DeleteSchemaRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    semver: String,
    idempotency_key: Option<String>,
}

impl DeleteSchemaRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, semver: String) -> Self {
        Self {
            client,
            namespace,
            slug,
            semver,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<serde_json::Value, crate::error::Error> {
        let path = format!("/v1/schemas/{}/{}/version/{}", crate::http::encode_path_param(&self.namespace), crate::http::encode_path_param(&self.slug), crate::http::encode_path_param(&self.semver));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body: Option<&serde_json::Value> = None;
        self.client
            .send::<serde_json::Value, _>(reqwest::Method::DELETE, &path, &query, &headers, body, true)
            .await
    }
}
/// Create a schema version.
#[must_use = "a request builder does nothing until `.send().await` is called"]
pub struct CreateSchemaRequest {
    client: crate::client::Scalar,
    namespace: String,
    slug: String,
    body: crate::models::VersionCreateSchemaBody,
    idempotency_key: Option<String>,
}

impl CreateSchemaRequest {
    fn new(client: crate::client::Scalar, namespace: String, slug: String, body: crate::models::VersionCreateSchemaBody) -> Self {
        Self {
            client,
            namespace,
            slug,
            body,
            idempotency_key: None,
        }
    }

    /// Sets an idempotency key so this request can be safely retried.
    pub fn idempotency_key(mut self, value: impl Into<String>) -> Self {
        self.idempotency_key = Some(value.into());
        self
    }

    /// Sends the request and returns the decoded response.
    pub async fn send(self) -> Result<crate::models::Uid, crate::error::Error> {
        let path = format!("/v1/schemas/{}/{}/version", crate::http::encode_path_param(&self.namespace), crate::http::encode_path_param(&self.slug));
        let query: Vec<(String, String)> = Vec::new();
        let mut headers: Vec<(String, String)> = Vec::new();
        if let Some(key) = self.idempotency_key {
            headers.push(("Idempotency-Key".to_string(), key));
        }
        let body = Some(&self.body);
        self.client
            .send::<crate::models::Uid, _>(reqwest::Method::POST, &path, &query, &headers, body, true)
            .await
    }
}
