// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Bring-your-own-transport example: the generated client running on
//! hyper 1.x instead of the bundled reqwest backend.
//!
//! `SdkBody` implements [`http_body::Body`], so the request passes to
//! hyper with **no conversion glue**; only the response body needs a
//! stream adapter back into `SdkBody`. Build it without reqwest at all:
//!
//! ```sh
//! cargo run --no-default-features --features tokio --example byo_transport_hyper
//! ```
#![allow(unused)]

use futures_util::StreamExt;
use hyper_util::client::legacy::Client;
use hyper_util::client::legacy::connect::HttpConnector;
use hyper_util::rt::TokioExecutor;

use scalar_sdk::transport::{BoxFuture, SdkBody, Transport, TransportError, TransportErrorKind};
use scalar_sdk::*;

/// Environment variable naming the server the guarded `main` dials.
const BASE_URL_ENV: &str = "SCALAR_BASE_URL";

/// A [`Transport`] backed by hyper via `hyper-util`'s legacy client.
///
/// Uses the plain-HTTP [`HttpConnector`] to keep this example free of a
/// TLS dependency; a production transport would wrap an HTTPS connector
/// (e.g. `hyper-rustls`) the same way. Everything above the wire —
/// retries, deadlines, auth, decoding — stays in the SDK runtime, so this
/// only moves one request and classifies failures.
struct HyperTransport {
    client: Client<HttpConnector, SdkBody>,
}

impl HyperTransport {
    fn new() -> Self {
        Self {
            client: Client::builder(TokioExecutor::new()).build_http(),
        }
    }
}

// Hand-written because `Client` exposes no useful `Debug` state; the
// `Transport` supertrait only needs the type to be printable.
impl std::fmt::Debug for HyperTransport {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str("HyperTransport")
    }
}

impl Transport for HyperTransport {
    fn execute(
        &self,
        request: ::http::Request<SdkBody>,
    ) -> BoxFuture<'_, Result<::http::Response<SdkBody>, TransportError>> {
        Box::pin(async move {
            // The zero-glue moment: the request goes to hyper as-is
            // because `SdkBody` is already an `http_body::Body`.
            let response = self.client.request(request).await.map_err(classify)?;
            // Adapt hyper's streaming body into `SdkBody` without
            // buffering, so large downloads stream through this backend.
            let (parts, body) = response.into_parts();
            let stream = http_body_util::BodyStream::new(body).filter_map(|frame| async move {
                match frame {
                    Ok(frame) => frame.into_data().ok().map(Ok),
                    Err(error) => Some(Err(TransportError::new(TransportErrorKind::Body, error))),
                }
            });
            Ok(::http::Response::from_parts(parts, SdkBody::from_stream(stream)))
        })
    }
}

/// Maps hyper's error onto the SDK's retry-relevant classification.
///
/// The mapping is load-bearing: `Connect` failures never reached the server
/// and are replayed for any method; everything else maps to `Other` and is
/// not retried. A finer-grained transport would classify timeouts too.
fn classify(error: hyper_util::client::legacy::Error) -> TransportError {
    let kind = if error.is_connect() {
        TransportErrorKind::Connect
    } else {
        TransportErrorKind::Other
    };
    TransportError::new(kind, error)
}

#[tokio::main]
async fn main() -> Result<(), Box<dyn std::error::Error>> {
    // Mirrors the smoke test's guard: the example always compiles but only
    // dials a server when explicitly pointed at one.
    let Ok(base_url) = std::env::var(BASE_URL_ENV) else {
        println!("Set {BASE_URL_ENV} to run this example against a server.");
        return Ok(());
    };
    let client = Scalar::builder()
        .base_url(base_url)
        .transport(HyperTransport::new())
        .build()?;
    let _ = client.registry().list_all_api_documents().send().await?;
    println!("request flowed through the hyper transport");
    Ok(())
}
