// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `access_groups`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

pub type AccessGroupName = String;

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccessGroupsCreateResponse {
    pub uid: String,
    pub name: String,
    pub slug: String,
    #[serde(rename = "allowedDomains")]
    pub allowed_domains: String,
    #[serde(rename = "allowedEmails")]
    pub allowed_emails: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AccessGroupsCreateBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "allowedDomains", default, skip_serializing_if = "Option::is_none")]
    pub allowed_domains: Option<String>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AccessGroupsRetrieveResponse {
    pub uid: String,
    pub name: String,
    pub slug: String,
    #[serde(rename = "allowedDomains")]
    pub allowed_domains: String,
    #[serde(rename = "allowedEmails")]
    pub allowed_emails: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct AccessGroupsUpdateBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
}
