// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `authentication`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

pub type Email = String;

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TeamSummary {
    pub uid: String,
    pub name: String,
    #[serde(rename = "imageUri", default, skip_serializing_if = "Option::is_none")]
    pub image_uri: Option<String>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct User {
    pub uid: String,
    #[serde(rename = "createdAt")]
    pub created_at: i64,
    #[serde(rename = "updatedAt")]
    pub updated_at: i64,
    pub email: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub theme: Option<String>,
    #[serde(rename = "activeTeamId", default)]
    pub active_team_id: Option<String>,
    #[serde(rename = "hasGithub")]
    pub has_github: bool,
    pub teams: Vec<TeamSummary>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct AuthenticationExchangePersonalTokenResponse {
    #[serde(rename = "accessToken")]
    pub access_token: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AuthenticationExchangePersonalTokenBody {
    #[serde(rename = "personalToken")]
    pub personal_token: String,
}
