// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `domains`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

pub type EmailDomain = String;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DomainsCreateBody {
    pub domain: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct DomainsDeleteBody {
    pub domain: String,
}
