// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `login_portals`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LoginPortalEmail {
    pub logo: String,
    #[serde(rename = "logoSize")]
    pub logo_size: String,
    #[serde(rename = "buttonText")]
    pub button_text: String,
    pub message: String,
    pub title: String,
    #[serde(rename = "mainColor")]
    pub main_color: String,
    #[serde(rename = "mainBackground")]
    pub main_background: String,
    #[serde(rename = "cardColor")]
    pub card_color: String,
    #[serde(rename = "cardBackground")]
    pub card_background: String,
    #[serde(rename = "buttonColor")]
    pub button_color: String,
    #[serde(rename = "buttonBackground")]
    pub button_background: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LoginPortalPage {
    pub title: String,
    pub description: String,
    pub head: String,
    pub script: String,
    pub theme: String,
    #[serde(rename = "companyName")]
    pub company_name: String,
    pub logo: String,
    #[serde(rename = "logoURL")]
    pub logo_url: String,
    pub favicon: String,
    #[serde(rename = "termsLink")]
    pub terms_link: String,
    #[serde(rename = "privacyLink")]
    pub privacy_link: String,
    #[serde(rename = "formTitle")]
    pub form_title: String,
    #[serde(rename = "formDescription")]
    pub form_description: String,
    #[serde(rename = "formImage")]
    pub form_image: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct LoginPortal {
    pub uid: String,
    pub title: String,
    pub slug: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct LoginPortalsRetrieveResponse {
    pub uid: String,
    pub title: String,
    pub slug: String,
    pub email: LoginPortalEmail,
    pub page: LoginPortalPage,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct LoginPortalsUpdateBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct LoginPortalsCreateBody {
    pub title: String,
    pub slug: String,
    pub email: LoginPortalEmail,
    pub page: LoginPortalPage,
}
