// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `members`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TeamMember {
    pub uid: String,
    pub role: Role,
    #[serde(rename = "displayName")]
    pub display_name: String,
    #[serde(rename = "imageUri", default, skip_serializing_if = "Option::is_none")]
    pub image_uri: Option<String>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct TeamInvite {
    pub uid: String,
    pub email: String,
    pub role: Role,
    #[serde(
        default,
        skip_serializing_if = "Option::is_none",
        serialize_with = "crate::number::option::serialize"
    )]
    pub expires: Option<f64>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct MembersListResponse {
    pub members: Vec<TeamMember>,
    #[serde(rename = "pendingInvites")]
    pub pending_invites: Vec<TeamInvite>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct MembersUpdateBody {
    pub role: Role,
}
