// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `registry`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ApiDocument {
    pub uid: String,
    pub version: String,
    pub title: String,
    pub slug: String,
    pub description: String,
    pub namespace: String,
    #[serde(rename = "isPrivate")]
    pub is_private: bool,
    pub tags: String,
    pub versions: Vec<ManagedDocVersion>,
}

pub type Version = String;

pub type Method = String;

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct AccessGroup {
    #[serde(rename = "accessGroupSlug")]
    pub access_group_slug: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct RegistryCreateApiDocumentResponse {
    pub uid: String,
    #[serde(rename = "versionUid")]
    pub version_uid: String,
    pub title: String,
    #[serde(rename = "jsonSha")]
    pub json_sha: String,
    #[serde(rename = "yamlSha")]
    pub yaml_sha: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RegistryCreateApiDocumentBody {
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub version: String,
    pub slug: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ruleset: Option<String>,
    #[serde(rename = "isPrivate", default, skip_serializing_if = "Option::is_none")]
    pub is_private: Option<bool>,
    pub document: String,
}

impl RegistryCreateApiDocumentBody {
    /// Creates a new `RegistryCreateApiDocumentBody` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `RegistryCreateApiDocumentBody { description: Some(…), ..RegistryCreateApiDocumentBody::new(…) }`.
    pub fn new(
        title: impl Into<String>,
        version: impl Into<String>,
        slug: impl Into<String>,
        document: impl Into<String>,
    ) -> Self {
        Self {
            title: title.into(),
            description: None,
            version: version.into(),
            slug: slug.into(),
            ruleset: None,
            is_private: None,
            document: document.into(),
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RegistryUpdateApiDocumentBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "isPrivate", default, skip_serializing_if = "Option::is_none")]
    pub is_private: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub ruleset: Option<String>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct RegistryUpdateApiDocumentVersionResponse {
    #[serde(rename = "jsonSha")]
    pub json_sha: String,
    #[serde(rename = "yamlSha")]
    pub yaml_sha: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RegistryUpdateApiDocumentVersionBody {
    pub document: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RegistryCreateApiDocumentVersionBody {
    pub version: String,
    pub document: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub force: Option<bool>,
}

impl RegistryCreateApiDocumentVersionBody {
    /// Creates a new `RegistryCreateApiDocumentVersionBody` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `RegistryCreateApiDocumentVersionBody { force: Some(…), ..RegistryCreateApiDocumentVersionBody::new(…) }`.
    pub fn new(version: impl Into<String>, document: impl Into<String>) -> Self {
        Self {
            version: version.into(),
            document: document.into(),
            force: None,
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ManagedDocVersionEmbedStatus {
    #[serde(rename = "complete")]
    Complete,
    #[serde(rename = "failed")]
    Failed,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ManagedDocVersionEmbedStatus {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Complete => "complete",
            Self::Failed => "failed",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ManagedDocVersionEmbedStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ManagedDocVersionEmbedStatus {
    fn from(value: &str) -> Self {
        match value {
            "complete" => Self::Complete,
            "failed" => Self::Failed,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ManagedDocVersionTool {
    pub path: String,
    pub method: String,
    #[serde(rename = "enabledTools")]
    pub enabled_tools: Vec<ManagedDocVersionToolEnabledTool>,
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum ManagedDocVersionToolEnabledTool {
    #[serde(rename = "execute-request")]
    ExecuteRequest,
    #[serde(rename = "get-mini-openapi-spec")]
    GetMiniOpenapiSpec,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl ManagedDocVersionToolEnabledTool {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::ExecuteRequest => "execute-request",
            Self::GetMiniOpenapiSpec => "get-mini-openapi-spec",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for ManagedDocVersionToolEnabledTool {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for ManagedDocVersionToolEnabledTool {
    fn from(value: &str) -> Self {
        match value {
            "execute-request" => Self::ExecuteRequest,
            "get-mini-openapi-spec" => Self::GetMiniOpenapiSpec,
            other => Self::Unknown(other.to_owned()),
        }
    }
}
