// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `rules`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Rule {
    pub uid: String,
    pub title: String,
    pub description: String,
    pub slug: String,
    pub namespace: String,
    #[serde(rename = "isPrivate")]
    pub is_private: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct RulesCreateRulesetBody {
    pub title: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub slug: String,
    #[serde(rename = "isPrivate", default, skip_serializing_if = "Option::is_none")]
    pub is_private: Option<bool>,
    pub document: String,
}

impl RulesCreateRulesetBody {
    /// Creates a new `RulesCreateRulesetBody` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `RulesCreateRulesetBody { description: Some(…), ..RulesCreateRulesetBody::new(title, slug, document) }`.
    pub fn new(title: impl Into<String>, slug: impl Into<String>, document: impl Into<String>) -> Self {
        Self {
            title: title.into(),
            description: None,
            slug: slug.into(),
            is_private: None,
            document: document.into(),
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct RulesUpdateRulesetBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub namespace: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    #[serde(rename = "isPrivate", default, skip_serializing_if = "Option::is_none")]
    pub is_private: Option<bool>,
}
