// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `sdks`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Sdk {
    pub uid: String,
    pub title: String,
    pub slug: String,
    pub namespace: String,
    pub description: String,
    #[serde(rename = "isPrivate")]
    pub is_private: bool,
    #[serde(rename = "apiUid", default)]
    pub api_uid: Option<String>,
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
    #[serde(rename = "currentVersion")]
    pub current_version: String,
    pub targets: Vec<SdkTargetSummary>,
    pub versions: Vec<SdkVersion>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SdkTargetSummary {
    pub language: SdkTargetSummaryLanguage,
    pub slug: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SdkVersion {
    pub version: String,
    #[serde(rename = "apiVersion")]
    pub api_version: String,
    pub status: SdkVersionStatus,
    pub languages: Vec<SdkVersionLanguage>,
    #[serde(rename = "publishedAt", default, skip_serializing_if = "Option::is_none")]
    pub published_at: Option<i64>,
    #[serde(rename = "createdAt", default, skip_serializing_if = "Option::is_none")]
    pub created_at: Option<i64>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SdksListResponse {
    pub data: Vec<Sdk>,
    #[serde(rename = "hasMore")]
    pub has_more: bool,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct SdksCreateBody {
    #[serde(rename = "apiUid")]
    pub api_uid: String,
    pub languages: Vec<SdksCreateBodyLanguage>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "className", default, skip_serializing_if = "Option::is_none")]
    pub class_name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<String>,
}

impl SdksCreateBody {
    /// Creates a new `SdksCreateBody` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `SdksCreateBody { title: Some(…), ..SdksCreateBody::new(api_uid, languages) }`.
    pub fn new(api_uid: impl Into<String>, languages: Vec<SdksCreateBodyLanguage>) -> Self {
        Self {
            api_uid: api_uid.into(),
            languages,
            title: None,
            slug: None,
            class_name: None,
            config: None,
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum SdksCreateBodyLanguage {
    #[serde(rename = "typescript")]
    Typescript,
    #[serde(rename = "python")]
    Python,
    #[serde(rename = "cli")]
    Cli,
    #[serde(rename = "csharp")]
    Csharp,
    #[serde(rename = "java")]
    Java,
    #[serde(rename = "ruby")]
    Ruby,
    #[serde(rename = "php")]
    Php,
    #[serde(rename = "go")]
    Go,
    #[serde(rename = "rust")]
    Rust,
    #[serde(rename = "kotlin")]
    Kotlin,
    #[serde(rename = "swift")]
    Swift,
    #[serde(rename = "cpp")]
    Cpp,
    #[serde(rename = "dart")]
    Dart,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl SdksCreateBodyLanguage {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Typescript => "typescript",
            Self::Python => "python",
            Self::Cli => "cli",
            Self::Csharp => "csharp",
            Self::Java => "java",
            Self::Ruby => "ruby",
            Self::Php => "php",
            Self::Go => "go",
            Self::Rust => "rust",
            Self::Kotlin => "kotlin",
            Self::Swift => "swift",
            Self::Cpp => "cpp",
            Self::Dart => "dart",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for SdksCreateBodyLanguage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for SdksCreateBodyLanguage {
    fn from(value: &str) -> Self {
        match value {
            "typescript" => Self::Typescript,
            "python" => Self::Python,
            "cli" => Self::Cli,
            "csharp" => Self::Csharp,
            "java" => Self::Java,
            "ruby" => Self::Ruby,
            "php" => Self::Php,
            "go" => Self::Go,
            "rust" => Self::Rust,
            "kotlin" => Self::Kotlin,
            "swift" => Self::Swift,
            "cpp" => Self::Cpp,
            "dart" => Self::Dart,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SdksUpdateBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub title: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "isPrivate", default, skip_serializing_if = "Option::is_none")]
    pub is_private: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub config: Option<String>,
    #[serde(rename = "apiUid", default, skip_serializing_if = "Option::is_none")]
    pub api_uid: Option<String>,
    #[serde(rename = "apiVersion", default, skip_serializing_if = "Option::is_none")]
    pub api_version: Option<String>,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct SdksBuildResponse {
    pub version: String,
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct SdksBuildBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub version: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub languages: Option<Vec<SdksBuildBodyLanguage>>,
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum SdksBuildBodyLanguage {
    #[serde(rename = "typescript")]
    Typescript,
    #[serde(rename = "python")]
    Python,
    #[serde(rename = "cli")]
    Cli,
    #[serde(rename = "csharp")]
    Csharp,
    #[serde(rename = "java")]
    Java,
    #[serde(rename = "ruby")]
    Ruby,
    #[serde(rename = "php")]
    Php,
    #[serde(rename = "go")]
    Go,
    #[serde(rename = "rust")]
    Rust,
    #[serde(rename = "kotlin")]
    Kotlin,
    #[serde(rename = "swift")]
    Swift,
    #[serde(rename = "cpp")]
    Cpp,
    #[serde(rename = "dart")]
    Dart,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl SdksBuildBodyLanguage {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Typescript => "typescript",
            Self::Python => "python",
            Self::Cli => "cli",
            Self::Csharp => "csharp",
            Self::Java => "java",
            Self::Ruby => "ruby",
            Self::Php => "php",
            Self::Go => "go",
            Self::Rust => "rust",
            Self::Kotlin => "kotlin",
            Self::Swift => "swift",
            Self::Cpp => "cpp",
            Self::Dart => "dart",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for SdksBuildBodyLanguage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for SdksBuildBodyLanguage {
    fn from(value: &str) -> Self {
        match value {
            "typescript" => Self::Typescript,
            "python" => Self::Python,
            "cli" => Self::Cli,
            "csharp" => Self::Csharp,
            "java" => Self::Java,
            "ruby" => Self::Ruby,
            "php" => Self::Php,
            "go" => Self::Go,
            "rust" => Self::Rust,
            "kotlin" => Self::Kotlin,
            "swift" => Self::Swift,
            "cpp" => Self::Cpp,
            "dart" => Self::Dart,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum SdkTargetSummaryLanguage {
    #[serde(rename = "typescript")]
    Typescript,
    #[serde(rename = "python")]
    Python,
    #[serde(rename = "cli")]
    Cli,
    #[serde(rename = "csharp")]
    Csharp,
    #[serde(rename = "java")]
    Java,
    #[serde(rename = "ruby")]
    Ruby,
    #[serde(rename = "php")]
    Php,
    #[serde(rename = "go")]
    Go,
    #[serde(rename = "rust")]
    Rust,
    #[serde(rename = "kotlin")]
    Kotlin,
    #[serde(rename = "swift")]
    Swift,
    #[serde(rename = "cpp")]
    Cpp,
    #[serde(rename = "dart")]
    Dart,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl SdkTargetSummaryLanguage {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Typescript => "typescript",
            Self::Python => "python",
            Self::Cli => "cli",
            Self::Csharp => "csharp",
            Self::Java => "java",
            Self::Ruby => "ruby",
            Self::Php => "php",
            Self::Go => "go",
            Self::Rust => "rust",
            Self::Kotlin => "kotlin",
            Self::Swift => "swift",
            Self::Cpp => "cpp",
            Self::Dart => "dart",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for SdkTargetSummaryLanguage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for SdkTargetSummaryLanguage {
    fn from(value: &str) -> Self {
        match value {
            "typescript" => Self::Typescript,
            "python" => Self::Python,
            "cli" => Self::Cli,
            "csharp" => Self::Csharp,
            "java" => Self::Java,
            "ruby" => Self::Ruby,
            "php" => Self::Php,
            "go" => Self::Go,
            "rust" => Self::Rust,
            "kotlin" => Self::Kotlin,
            "swift" => Self::Swift,
            "cpp" => Self::Cpp,
            "dart" => Self::Dart,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum SdkVersionStatus {
    #[serde(rename = "draft")]
    Draft,
    #[serde(rename = "published")]
    Published,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl SdkVersionStatus {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Draft => "draft",
            Self::Published => "published",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for SdkVersionStatus {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for SdkVersionStatus {
    fn from(value: &str) -> Self {
        match value {
            "draft" => Self::Draft,
            "published" => Self::Published,
            other => Self::Unknown(other.to_owned()),
        }
    }
}

/// Match on `as_str()` (or build one with `From<&str>`) when you need a value
/// this SDK version does not know. Matching `Unknown(_)` directly is an
/// anti-pattern: that arm silently stops matching once a future SDK release
/// adds the real variant.
#[derive(Debug, Clone, PartialEq, Eq, Serialize, Deserialize)]
#[non_exhaustive]
pub enum SdkVersionLanguage {
    #[serde(rename = "typescript")]
    Typescript,
    #[serde(rename = "python")]
    Python,
    #[serde(rename = "cli")]
    Cli,
    #[serde(rename = "csharp")]
    Csharp,
    #[serde(rename = "java")]
    Java,
    #[serde(rename = "ruby")]
    Ruby,
    #[serde(rename = "php")]
    Php,
    #[serde(rename = "go")]
    Go,
    #[serde(rename = "rust")]
    Rust,
    #[serde(rename = "kotlin")]
    Kotlin,
    #[serde(rename = "swift")]
    Swift,
    #[serde(rename = "cpp")]
    Cpp,
    #[serde(rename = "dart")]
    Dart,
    /// A value not known to this version of the SDK, preserved verbatim.
    #[serde(untagged)]
    Unknown(String),
}

impl SdkVersionLanguage {
    /// The wire value this variant serializes to.
    pub fn as_str(&self) -> &str {
        match self {
            Self::Typescript => "typescript",
            Self::Python => "python",
            Self::Cli => "cli",
            Self::Csharp => "csharp",
            Self::Java => "java",
            Self::Ruby => "ruby",
            Self::Php => "php",
            Self::Go => "go",
            Self::Rust => "rust",
            Self::Kotlin => "kotlin",
            Self::Swift => "swift",
            Self::Cpp => "cpp",
            Self::Dart => "dart",
            Self::Unknown(value) => value,
        }
    }
}

impl std::fmt::Display for SdkVersionLanguage {
    fn fmt(&self, f: &mut std::fmt::Formatter<'_>) -> std::fmt::Result {
        f.write_str(self.as_str())
    }
}

impl From<&str> for SdkVersionLanguage {
    fn from(value: &str) -> Self {
        match value {
            "typescript" => Self::Typescript,
            "python" => Self::Python,
            "cli" => Self::Cli,
            "csharp" => Self::Csharp,
            "java" => Self::Java,
            "ruby" => Self::Ruby,
            "php" => Self::Php,
            "go" => Self::Go,
            "rust" => Self::Rust,
            "kotlin" => Self::Kotlin,
            "swift" => Self::Swift,
            "cpp" => Self::Cpp,
            "dart" => Self::Dart,
            other => Self::Unknown(other.to_owned()),
        }
    }
}
