// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `servers`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct McpServer {
    pub id: String,
    pub name: String,
    pub slug: String,
    #[serde(rename = "autoAddOperations")]
    pub auto_add_operations: bool,
    #[serde(rename = "createdAt")]
    pub created_at: String,
    #[serde(rename = "updatedAt")]
    pub updated_at: String,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct McpInstallation {
    pub id: String,
    #[serde(rename = "mcpServerId")]
    pub mcp_server_id: String,
    pub name: String,
    pub slug: String,
    #[serde(rename = "isPrivate")]
    pub is_private: bool,
    #[serde(rename = "accessGroups")]
    pub access_groups: Vec<String>,
    #[serde(rename = "loginPortalUid", default)]
    pub login_portal_uid: Option<String>,
    #[serde(rename = "mcpVersion", default)]
    pub mcp_version: Option<String>,
    #[serde(rename = "piiRedactionEnabled")]
    pub pii_redaction_enabled: bool,
    #[serde(rename = "credentialRedactionEnabled")]
    pub credential_redaction_enabled: bool,
}

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct ServersCreateResponse {
    pub server: McpServer,
    pub installation: McpInstallation,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ServersCreateBody {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "versionUids", default, skip_serializing_if = "Option::is_none")]
    pub version_uids: Option<Vec<String>>,
    #[serde(rename = "projectUids", default, skip_serializing_if = "Option::is_none")]
    pub project_uids: Option<Vec<String>>,
}

impl ServersCreateBody {
    /// Creates a new `ServersCreateBody` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `ServersCreateBody { slug: Some(…), ..ServersCreateBody::new(name) }`.
    pub fn new(name: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            slug: None,
            version_uids: None,
            project_uids: None,
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ServersUpdateBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub slug: Option<String>,
    #[serde(rename = "autoAddOperations", default, skip_serializing_if = "Option::is_none")]
    pub auto_add_operations: Option<bool>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub operations: Option<Vec<String>>,
    #[serde(rename = "docsPages", default, skip_serializing_if = "Option::is_none")]
    pub docs_pages: Option<Vec<String>>,
}
