// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `themes`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

///
/// Response-only model, marked `#[non_exhaustive]`: fields may be added
/// additively in future versions without a breaking release.
#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
#[non_exhaustive]
pub struct Theme {
    pub uid: String,
    pub name: String,
    pub description: String,
    pub slug: String,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ThemesCreateBody {
    pub name: String,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
    pub slug: String,
    pub document: String,
}

impl ThemesCreateBody {
    /// Creates a new `ThemesCreateBody` from its required fields, leaving every optional one unset.
    ///
    /// Pair it with struct-update syntax to set only the optionals you need:
    /// `ThemesCreateBody { description: Some(…), ..ThemesCreateBody::new(name, slug, document) }`.
    pub fn new(name: impl Into<String>, slug: impl Into<String>, document: impl Into<String>) -> Self {
        Self {
            name: name.into(),
            description: None,
            slug: slug.into(),
            document: document.into(),
        }
    }
}

#[derive(Debug, Clone, Default, PartialEq, Serialize, Deserialize)]
pub struct ThemesUpdateBody {
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub name: Option<String>,
    #[serde(default, skip_serializing_if = "Option::is_none")]
    pub description: Option<String>,
}

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct ThemesReplaceDocumentBody {
    pub document: String,
}
