// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `versions`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VersionsCreateBody {
    pub version: String,
    #[serde(rename = "apiVersion")]
    pub api_version: String,
}
