// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Generated request and response models declared under `version`.

#[allow(unused_imports)]
use super::*;
use serde::{Deserialize, Serialize};

#[derive(Debug, Clone, PartialEq, Serialize, Deserialize)]
pub struct VersionCreateBody {
    pub version: String,
    pub document: String,
}
