// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Request runtime: retry policy, backoff, deadlines, and response decoding.
//!
//! This module is request-shape agnostic — it never touches authentication or
//! per-operation parameters (the generated client owns those). It exists so
//! retry, backoff, deadline, and error-mapping logic lives in one audited place
//! instead of being duplicated across every operation. All I/O goes through the
//! [`Transport`] and [`Sleep`] abstractions, so the same policy applies to the
//! bundled backend and to any BYO transport.

use std::time::Duration;

use bytes::Bytes;
use futures_util::StreamExt;
use futures_util::future::{Either, select};
use http::HeaderMap;
use serde::Serialize;
use serde::de::DeserializeOwned;

use crate::error::{ApiError, Error};
use crate::transport::{SdkBody, Sleep, Transport, TransportError, TransportErrorKind};

/// Header inspected for a server-assigned request id used in error reports.
const REQUEST_ID_HEADER: &str = "x-request-id";

/// Default cap on buffered response bodies, in bytes (64 MiB).
///
/// Response bodies are attacker-influencable input; buffering them without a
/// bound hands a hostile or misconfigured server an out-of-memory primitive.
/// The client builder overrides this per client; streaming responses are not
/// buffered and therefore not subject to the cap.
pub(crate) const DEFAULT_MAX_RESPONSE_SIZE: usize = 64 * 1024 * 1024;

/// Cap on how many bytes of a discarded retryable-status body are drained
/// before the next attempt (64 KiB).
///
/// Reading a small 429/5xx error body to completion lets an HTTP/1.1
/// connection return to the pool for keep-alive reuse during retry storms
/// instead of being torn down and re-established on every attempt. A body
/// larger than the cap simply abandons the drain — dropping the stream closes
/// the connection, exactly as if no drain had been attempted — so the cap is
/// an opportunistic optimization bound, never a correctness requirement.
const RETRY_DRAIN_LIMIT: usize = 64 * 1024;

/// Upper bound on honoring a server-provided `Retry-After` delay (60 s).
///
/// Deliberately separate from [`RetryPolicy::max_backoff`], which caps only
/// the client's own exponential backoff: clamping a `Retry-After: 45` down to
/// 8 s would replay straight into the same rate-limit window. Within the
/// ceiling the server's delay is honored in full; above it the retry is
/// abandoned and the response returned as the terminal result — the server
/// has told us to go away for longer than we are willing to stall the caller.
const RETRY_AFTER_CEILING: Duration = Duration::from_secs(60);

/// Structured [`tracing`](https://docs.rs/tracing) instrumentation for the
/// request runtime, compiled only with the `tracing` cargo feature.
///
/// Two `#[cfg]` flavors of the same private API exist so every call site in
/// this module stays unconditional: with the feature on these functions emit
/// events, with it off they are empty bodies that optimize away and the crate
/// carries no `tracing` dependency at all. This crate is a library — it emits
/// events and never installs a subscriber; wiring one up (`tracing-subscriber`,
/// `RUST_LOG`, …) belongs to the application binary.
///
/// # Redaction
///
/// Everything logged is derived from a request/response *envelope* and nothing
/// else. URLs pass through [`crate::error::redact_url`] because API keys and
/// signed tokens routinely ride in query parameters; header values are never
/// read (not even their names); request and response bodies are never touched;
/// and error values are reduced to a static class label rather than rendered,
/// since a transport or API error can carry server-supplied text. Keep any new
/// event inside those bounds — trace output ends up in logs and bug reports
/// exactly like the `Debug` output the error types already redact.
///
/// # Stability
///
/// Event targets, messages, and field names are diagnostics, not API: they may
/// change in any release and are not covered by semver.
#[cfg(feature = "tracing")]
mod trace {
    /// One request attempt is about to be dispatched. `attempt` is zero-based,
    /// so `attempt = 0` is the original request and `1..` are replays.
    pub(super) fn attempt(method: &http::Method, uri: &http::Uri, attempt: u32) {
        let url = crate::error::redact_url(&uri.to_string());
        tracing::debug!(method = %method, url = %url, attempt, "sending request");
    }

    /// A retryable status was received and a replay was scheduled. `source`
    /// records whether the delay came from the server's `Retry-After` header or
    /// from the client's own exponential backoff.
    pub(super) fn retry_status(status: http::StatusCode, delay: std::time::Duration, source: &'static str) {
        tracing::debug!(
            status = status.as_u16(),
            delay_ms = millis(delay),
            source,
            "retrying request"
        );
    }

    /// A transient transport failure was classified as retryable and a replay
    /// was scheduled. Only the retry-relevant `kind` is logged — the error's
    /// message carries server/transport-supplied text.
    pub(super) fn retry_transport(error: &crate::transport::TransportError, delay: std::time::Duration) {
        tracing::debug!(error_kind = ?error.kind(), delay_ms = millis(delay), "retrying request");
    }

    /// Renders a backoff delay as whole milliseconds.
    ///
    /// `Duration::as_millis` is `u128`, which is not a `tracing` field value on
    /// every supported version; saturating into `u64` keeps the field a plain
    /// integer without a lossy `as` cast.
    fn millis(delay: std::time::Duration) -> u64 {
        u64::try_from(delay.as_millis()).unwrap_or(u64::MAX)
    }

    /// The request finished with a response (of any status); `attempts` counts
    /// the dispatches it took, so `1` means no retry happened.
    pub(super) fn completed(status: http::StatusCode, attempts: u32) {
        tracing::debug!(status = status.as_u16(), attempts, "request completed");
    }

    /// Every allowed attempt failed at the transport level.
    pub(super) fn failed(error: &crate::transport::TransportError, attempts: u32) {
        tracing::debug!(error_kind = ?error.kind(), attempts, "request failed");
    }

    /// A success response could not be turned into the operation's return type.
    /// Only the status and an error class are logged, never the body that
    /// failed to decode.
    pub(super) fn decode_failed(status: http::StatusCode, error: &crate::error::Error) {
        tracing::debug!(
            status = status.as_u16(),
            error_class = class(error),
            "response decode failed"
        );
    }

    /// An OAuth client-credentials exchange failed and the request authenticated
    /// with another configured credential instead. Deliberately field-free: the
    /// exchange error can carry server-supplied text, and the credential that
    /// took over must not be named.
    pub(super) fn oauth_fallback() {
        tracing::warn!("oauth token exchange failed; applying an alternative credential");
    }

    /// Reduces an [`crate::error::Error`] to a static, body-free label.
    ///
    /// The wildcard arm is load-bearing: `Error` is `#[non_exhaustive]` and
    /// grows over time, and an arm per variant would make every new variant a
    /// compile error in this diagnostics-only helper.
    fn class(error: &crate::error::Error) -> &'static str {
        match error {
            crate::error::Error::Api(_) => "api",
            crate::error::Error::Transport(_) => "transport",
            crate::error::Error::Serde(_) => "serde",
            crate::error::Error::ResponseTooLarge { .. } => "response_too_large",
            _ => "other",
        }
    }
}

/// No-op counterpart to the instrumented [`trace`] module, compiled when the
/// `tracing` feature is off so the call sites need no `#[cfg]` of their own.
///
/// The signatures must stay byte-for-byte compatible with the instrumented
/// flavor above; the bodies are empty, so the arguments are computed and
/// discarded (all of them are `Copy` reads or borrows) and the whole thing
/// optimizes out.
#[cfg(not(feature = "tracing"))]
mod trace {
    pub(super) fn attempt(_: &http::Method, _: &http::Uri, _: u32) {}
    pub(super) fn retry_status(_: http::StatusCode, _: std::time::Duration, _: &'static str) {}
    pub(super) fn retry_transport(_: &crate::transport::TransportError, _: std::time::Duration) {}
    pub(super) fn completed(_: http::StatusCode, _: u32) {}
    pub(super) fn failed(_: &crate::transport::TransportError, _: u32) {}
    pub(super) fn decode_failed(_: http::StatusCode, _: &crate::error::Error) {}
    pub(super) fn oauth_fallback() {}
}

/// Records that a failed client-credentials exchange fell back to another
/// configured credential.
///
/// Lives here so the generated client reaches the same feature-gated,
/// redaction-reviewed instrumentation the runtime uses instead of growing its
/// own. Unused — hence the allow — in crates whose SDK declares no OAuth
/// client-credentials flow, or whose credentials have no OR alternatives.
#[allow(dead_code)]
pub(crate) fn trace_oauth_fallback() {
    trace::oauth_fallback();
}

/// Retry policy applied to every request issued by the client.
///
/// Retries cover transient transport failures and retryable status codes (see
/// [`should_retry_status`]). Backoff grows exponentially from
/// `initial_backoff`, capped at `max_backoff`; a `Retry-After` response header
/// overrides the computed delay when present (see [`RETRY_AFTER_CEILING`]).
///
/// Crate-internal on purpose: callers configure retries through
/// `ClientBuilder::max_retries` (or the per-request `.max_retries()`
/// override), so a public policy struct would be semver surface with no
/// settable behavior behind it.
#[derive(Debug, Clone)]
pub(crate) struct RetryPolicy {
    /// Maximum number of retry attempts after the initial request.
    pub(crate) max_retries: u32,
    /// Delay before the first retry.
    pub(crate) initial_backoff: Duration,
    /// Upper bound on any single exponential-backoff delay.
    pub(crate) max_backoff: Duration,
}

impl RetryPolicy {
    /// Creates a policy with sensible exponential-backoff bounds.
    pub(crate) fn new(max_retries: u32) -> Self {
        Self {
            max_retries,
            initial_backoff: Duration::from_millis(500),
            max_backoff: Duration::from_secs(8),
        }
    }
}

/// Sends a request through `transport`, retrying transient failures.
///
/// The request is replayed via [`clone_request`] for each attempt; a
/// non-replayable body (a one-shot stream, where [`SdkBody::try_replay`]
/// returns `None`) disables retries and is sent exactly once — use
/// `SdkBody::from_retryable_stream` to opt a streamed upload into retries.
/// Returns the final response regardless of status — status-based error
/// mapping happens in [`decode_json`] so callers that want the raw response
/// can opt out.
///
/// `deadline`, when set, bounds each attempt (per attempt: every retry races
/// a fresh timer, so retries multiply total wall time) from dispatch until
/// response headers arrive by racing `transport.execute` against
/// `sleep.sleep(deadline)` — so a BYO transport cannot silently drop timeouts.
/// The race spans the whole `execute`, which includes uploading the request
/// body; that is why the generated client applies its *default* deadline only
/// to buffered non-multipart request bodies and passes `None` for streaming
/// and multipart uploads (an explicit caller-set timeout is passed for every
/// request — the caller asked for it). Once headers arrive the response body
/// is a stream, and a slow or long-lived body (SSE, large download) is never
/// deadline-killed.
///
/// `keyed` is set by the caller when the request carries an idempotency key, so
/// a possibly-processed failure (see [`should_retry_status`]) on a
/// non-idempotent method (POST/PATCH) can still be safely replayed — the
/// server deduplicates the retry by that key.
///
/// # Errors
///
/// Returns [`Error::Transport`] when every allowed attempt failed at the
/// transport level (connection, timeout, protocol) or the deadline elapsed
/// before response headers arrived.
pub async fn send_with_retries(
    transport: &dyn Transport,
    sleep: &dyn Sleep,
    request: http::Request<SdkBody>,
    max_retries: u32,
    deadline: Option<Duration>,
    keyed: bool,
) -> Result<http::Response<SdkBody>, Error> {
    let policy = RetryPolicy::new(max_retries);
    // Whether a *possibly-processed* failure may be replayed: retrying a
    // POST/PATCH that the server already processed (but whose response was
    // lost to a 5xx or a timeout) would duplicate the side effect — unless an
    // idempotency key lets the server dedupe the replay. Rejected-without-
    // processing statuses (408/429/503) and failed *connections* never ran the
    // request, so they retry for any method (see should_retry_status and
    // is_retryable_transport).
    let idempotent = keyed || is_idempotent(request.method());
    let mut attempt: u32 = 0;
    loop {
        // A one-shot streaming body cannot be replayed; send the original once
        // (still under the deadline) and stop.
        let Some(current) = clone_request(&request) else {
            trace::attempt(request.method(), request.uri(), attempt);
            return match execute_with_deadline(transport, sleep, request, deadline).await {
                Ok(response) => {
                    trace::completed(response.status(), attempt + 1);
                    Ok(response)
                }
                Err(error) => {
                    trace::failed(&error, attempt + 1);
                    Err(Error::from(error))
                }
            };
        };
        trace::attempt(current.method(), current.uri(), attempt);
        match execute_with_deadline(transport, sleep, current, deadline).await {
            Ok(response) => {
                if attempt < policy.max_retries && should_retry_status(response.status().as_u16(), idempotent) {
                    // `source` is carried alongside the delay purely so the
                    // retry event can say whether the server dictated the wait.
                    let (delay, source) = match retry_after(response.headers()) {
                        // The server named a delay past what we will wait out:
                        // do not retry — hand the response back as the terminal
                        // result instead of stalling the caller's future.
                        Some(after) if after > RETRY_AFTER_CEILING => {
                            trace::completed(response.status(), attempt + 1);
                            return Ok(response);
                        }
                        // Within the ceiling the server's delay is honored in
                        // full: sleeping less (e.g. clamping to max_backoff)
                        // would replay into the same rate-limit window.
                        Some(after) => (after, "retry-after"),
                        None => (backoff(&policy, attempt), "backoff"),
                    };
                    trace::retry_status(response.status(), delay, source);
                    attempt += 1;
                    // Drain the discarded error body (bounded) before backing
                    // off so the connection can be kept alive for the retry.
                    drain_for_reuse(response.into_body()).await;
                    sleep.sleep(delay).await;
                    continue;
                }
                trace::completed(response.status(), attempt + 1);
                return Ok(response);
            }
            Err(error) => {
                if attempt < policy.max_retries && is_retryable_transport(&error, idempotent) {
                    let delay = backoff(&policy, attempt);
                    trace::retry_transport(&error, delay);
                    sleep.sleep(delay).await;
                    attempt += 1;
                    continue;
                }
                trace::failed(&error, attempt + 1);
                return Err(Error::from(error));
            }
        }
    }
}

/// Executes one attempt, racing the transport against the deadline timer.
///
/// The race uses `select` over two already-boxed (`Unpin`) futures, so
/// whichever resolves first wins and the loser is dropped — dropping the
/// transport future cancels the in-flight request. The race covers everything
/// up to response headers, request-body upload included (which is why the
/// client only defaults a deadline for buffered bodies); the response *body*
/// is a stream consumed after this function returns and is intentionally
/// outside the race.
async fn execute_with_deadline(
    transport: &dyn Transport,
    sleep: &dyn Sleep,
    request: http::Request<SdkBody>,
    deadline: Option<Duration>,
) -> Result<http::Response<SdkBody>, TransportError> {
    let attempt = transport.execute(request);
    match deadline {
        None => attempt.await,
        Some(limit) => match select(attempt, sleep.sleep(limit)).await {
            Either::Left((result, _timer)) => result,
            Either::Right(((), _attempt)) => Err(TransportError::new(
                TransportErrorKind::Timeout,
                format!("no response headers within the {limit:?} deadline"),
            )),
        },
    }
}

/// Rebuilds a request for another retry attempt, or `None` if the body is a
/// one-shot stream.
///
/// `http::Request` is deliberately not `Clone` (the body may be a stream), so
/// the parts are copied field by field onto a replayed body. Extensions are
/// propagated too — per-request policy hints ride there and must survive
/// retries.
pub(crate) fn clone_request(request: &http::Request<SdkBody>) -> Option<http::Request<SdkBody>> {
    let body = request.body().try_replay()?;
    let mut clone = http::Request::new(body);
    *clone.method_mut() = request.method().clone();
    *clone.uri_mut() = request.uri().clone();
    *clone.version_mut() = request.version();
    *clone.headers_mut() = request.headers().clone();
    *clone.extensions_mut() = request.extensions().clone();
    Some(clone)
}

/// Buffers a success-path response body, aborting once it exceeds `cap` bytes.
///
/// The cap is enforced chunk by chunk while streaming — not after collecting —
/// so an over-limit body never occupies more than `cap` bytes of memory before
/// the read is abandoned. Error-path bodies go through [`collect_truncated`]
/// instead, which never fails.
///
/// # Errors
///
/// Returns [`Error::ResponseTooLarge`] when the body exceeds `cap`, or
/// [`Error::Transport`] when the underlying stream fails mid-read.
pub(crate) async fn collect_capped(body: SdkBody, cap: usize) -> Result<Bytes, Error> {
    let mut stream = body.into_data_stream();
    let mut collected: Vec<u8> = Vec::new();
    while let Some(chunk) = stream.next().await {
        let chunk = chunk.map_err(Error::from)?;
        if collected.len().saturating_add(chunk.len()) > cap {
            return Err(Error::ResponseTooLarge { limit: cap });
        }
        collected.extend_from_slice(&chunk);
    }
    Ok(Bytes::from(collected))
}

/// Buffers a non-success (error) response body, truncating instead of failing.
///
/// Unlike [`collect_capped`], nothing here can destroy the diagnosis: for an
/// error response the status, headers, and request id already in hand are what
/// the caller needs, so an over-cap body keeps its first `cap` bytes and a
/// mid-read stream failure keeps whatever arrived — either way the `bool`
/// reports the loss and the [`ApiError`] is always built. A 502 serving a
/// 200 KB HTML page must not become `Error::ResponseTooLarge`.
pub(crate) async fn collect_truncated(body: SdkBody, cap: usize) -> (Bytes, bool) {
    let mut stream = body.into_data_stream();
    let mut collected: Vec<u8> = Vec::new();
    let mut truncated = false;
    while let Some(chunk) = stream.next().await {
        let Ok(chunk) = chunk else {
            truncated = true;
            break;
        };
        let remaining = cap.saturating_sub(collected.len());
        if chunk.len() > remaining {
            collected.extend_from_slice(&chunk[..remaining]);
            truncated = true;
            break;
        }
        collected.extend_from_slice(&chunk);
    }
    (Bytes::from(collected), truncated)
}

/// Decodes a JSON response, mapping non-success statuses to [`ApiError`].
///
/// Success bodies are deserialized into `T`. For operations that return no
/// content, use [`decode_empty`] instead so an empty 2xx body is not fed to a
/// JSON deserializer. `cap` bounds how many body bytes are buffered (see
/// [`collect_capped`]).
///
/// # Errors
///
/// Returns [`Error::Api`] for a non-success status (its body truncated at
/// `cap`, never `ResponseTooLarge`), [`Error::Serde`] when the success body
/// does not match `T`, [`Error::ResponseTooLarge`] when a success body exceeds
/// `cap`, or [`Error::Transport`] when a success body stream fails mid-read.
pub async fn decode_json<T: DeserializeOwned>(response: http::Response<SdkBody>, cap: usize) -> Result<T, Error> {
    let (parts, body) = response.into_parts();
    let request_id = request_id(&parts.headers);
    // Status first: only success bodies may fail collection. Collecting before
    // checking would let an oversized error page (a 502 serving HTML) surface
    // as ResponseTooLarge, destroying the status/headers/request id.
    if parts.status.is_success() {
        // Decode failures on the success path are the ones worth tracing: a
        // non-success status is already reported as the terminal outcome by
        // `send_with_retries` and surfaces to the caller as a typed `ApiError`.
        let bytes = collect_capped(body, cap)
            .await
            .inspect_err(|error| trace::decode_failed(parts.status, error))?;
        // A successful response with an empty body (a 204, or a 200/202 with no
        // content) is not valid JSON; decode it as `null` so `Option<T>` and
        // unit-like return types succeed instead of failing with an EOF error.
        if bytes.is_empty() {
            return serde_json::from_slice(b"null")
                .map_err(Error::from)
                .inspect_err(|error| trace::decode_failed(parts.status, error));
        }
        serde_json::from_slice(&bytes)
            .map_err(Error::from)
            .inspect_err(|error| trace::decode_failed(parts.status, error))
    } else {
        let (bytes, truncated) = collect_truncated(body, cap).await;
        Err(Error::from(ApiError::from_parts(
            parts.status.as_u16(),
            parts.headers,
            request_id,
            &bytes,
            truncated,
        )))
    }
}

/// Decodes a binary response body, mapping non-success statuses to [`ApiError`].
///
/// Used for operations whose success response is a non-JSON payload
/// (`application/octet-stream`, `text/csv`, etc.): the bytes are returned
/// verbatim rather than fed to a JSON deserializer. `cap` bounds how many body
/// bytes are buffered (see [`collect_capped`]).
///
/// # Errors
///
/// Returns [`Error::Api`] for a non-success status (its body truncated at
/// `cap`), [`Error::ResponseTooLarge`] when a success body exceeds `cap`, or
/// [`Error::Transport`] when a success body stream fails mid-read.
pub async fn decode_bytes(response: http::Response<SdkBody>, cap: usize) -> Result<Bytes, Error> {
    let (parts, body) = response.into_parts();
    let request_id = request_id(&parts.headers);
    // Status first — see `decode_json` for why error bodies must not be able
    // to fail collection.
    if parts.status.is_success() {
        collect_capped(body, cap)
            .await
            .inspect_err(|error| trace::decode_failed(parts.status, error))
    } else {
        let (bytes, truncated) = collect_truncated(body, cap).await;
        Err(Error::from(ApiError::from_parts(
            parts.status.as_u16(),
            parts.headers,
            request_id,
            &bytes,
            truncated,
        )))
    }
}

/// Consumes a no-content response, mapping non-success statuses to [`ApiError`].
///
/// `cap` bounds how many error-body bytes are kept (see [`collect_truncated`]);
/// a success response's body is drained (bounded) rather than parsed, so a
/// keep-alive connection stays reusable even when a "no content" operation
/// returns stray body bytes.
///
/// # Errors
///
/// Returns [`Error::Api`] for a non-success status, its body truncated at
/// `cap`.
pub async fn decode_empty(response: http::Response<SdkBody>, cap: usize) -> Result<(), Error> {
    let (parts, body) = response.into_parts();
    let request_id = request_id(&parts.headers);
    if parts.status.is_success() {
        drain_for_reuse(body).await;
        Ok(())
    } else {
        let (bytes, truncated) = collect_truncated(body, cap).await;
        Err(Error::from(ApiError::from_parts(
            parts.status.as_u16(),
            parts.headers,
            request_id,
            &bytes,
            truncated,
        )))
    }
}

/// Drains up to [`RETRY_DRAIN_LIMIT`] bytes of a response body being discarded
/// before a retry, so a keep-alive connection can be reused for the next
/// attempt.
///
/// A mid-read error or an over-limit body just stops the drain: the stream is
/// dropped, which closes the connection — the same outcome as not draining at
/// all — so errors are deliberately ignored here.
async fn drain_for_reuse(body: SdkBody) {
    let mut stream = body.into_data_stream();
    let mut drained: usize = 0;
    while let Some(chunk) = stream.next().await {
        let Ok(chunk) = chunk else { return };
        drained = drained.saturating_add(chunk.len());
        if drained > RETRY_DRAIN_LIMIT {
            return;
        }
    }
}

/// Extracts the request-id header value, if present and valid UTF-8.
pub(crate) fn request_id(headers: &HeaderMap) -> Option<String> {
    headers
        .get(REQUEST_ID_HEADER)
        .and_then(|value| value.to_str().ok())
        .map(str::to_owned)
}

/// Whether a response status is worth retrying for this request.
///
/// The taxonomy splits on whether the server may have run the request:
///
/// - 408 (request timeout), 429 (rate limited), and 503 (unavailable) mean the
///   request was REJECTED without being processed, so a replay cannot
///   duplicate a side effect — every method retries these, POST included.
/// - Other 5xx (500, 502, 504, …) may have executed before failing, so they
///   replay only when the request is idempotent or carries an idempotency key
///   the server can dedupe on.
///
/// 409 Conflict is deliberately NOT retried: it reports a semantic conflict
/// (version mismatch, duplicate resource) that an identical replay cannot
/// resolve — blindly retrying it only hammers the server. 501 Not Implemented
/// is excluded from the retryable 5xx for the same reason: it is a permanent
/// condition (the server does not support the method), so no replay can ever
/// succeed.
fn should_retry_status(status: u16, idempotent: bool) -> bool {
    match status {
        408 | 429 | 503 => true,
        // 501 is permanent — the server does not implement the request — so
        // replaying an identical request can never produce a different result.
        501 => false,
        _ => idempotent && status >= 500,
    }
}

/// Whether a request method is safe to replay (RFC 7231 idempotent methods).
fn is_idempotent(method: &http::Method) -> bool {
    matches!(
        *method,
        http::Method::GET
            | http::Method::HEAD
            | http::Method::PUT
            | http::Method::DELETE
            | http::Method::OPTIONS
            | http::Method::TRACE
    )
}

/// Whether a transport error is transient enough to retry.
///
/// A `Connect` failure means the request never reached the server, so it is
/// safe to retry for any method. A `Timeout` may have been received and
/// processed by the server, so it is only replayed for idempotent (or
/// idempotency-keyed) requests. This classification is load-bearing: a BYO
/// transport that lumps everything into `Other` loses connect-retry.
fn is_retryable_transport(error: &TransportError, idempotent: bool) -> bool {
    match error.kind() {
        TransportErrorKind::Connect => true,
        TransportErrorKind::Timeout => idempotent,
        _ => false,
    }
}

/// Parses a `Retry-After` header, in either RFC 7231 form.
///
/// The value is `delta-seconds` (a whole number) or an HTTP-date; the latter is
/// resolved to a delay from now (servers commonly send it on 429/503). The
/// caller honors the delay in full up to [`RETRY_AFTER_CEILING`] and abandons
/// the retry beyond it.
fn retry_after(headers: &HeaderMap) -> Option<Duration> {
    let value = headers.get(http::header::RETRY_AFTER)?.to_str().ok()?.trim();
    if let Ok(seconds) = value.parse::<u64>() {
        return Some(Duration::from_secs(seconds));
    }
    retry_after_date(value).map(Duration::from_secs)
}

/// Resolves an HTTP-date `Retry-After` (IMF-fixdate, e.g.
/// `Wed, 21 Oct 2015 07:28:00 GMT`) into seconds from now, `0` if already past.
///
/// Parsed without a date dependency so the transport runtime stays
/// zero-dependency regardless of whether the SDK pulls in `chrono`.
fn retry_after_date(value: &str) -> Option<u64> {
    let parts: Vec<&str> = value.split_whitespace().collect();
    if parts.len() != 6 {
        return None;
    }
    let day: i64 = parts[1].parse().ok()?;
    let month = match parts[2] {
        "Jan" => 1,
        "Feb" => 2,
        "Mar" => 3,
        "Apr" => 4,
        "May" => 5,
        "Jun" => 6,
        "Jul" => 7,
        "Aug" => 8,
        "Sep" => 9,
        "Oct" => 10,
        "Nov" => 11,
        "Dec" => 12,
        _ => return None,
    };
    let year: i64 = parts[3].parse().ok()?;
    let time: Vec<&str> = parts[4].split(':').collect();
    if time.len() != 3 {
        return None;
    }
    let hour: i64 = time[0].parse().ok()?;
    let minute: i64 = time[1].parse().ok()?;
    let second: i64 = time[2].parse().ok()?;
    let target = days_from_civil(year, month, day) * 86_400 + hour * 3_600 + minute * 60 + second;
    let now = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .ok()?
        .as_secs() as i64;
    Some((target - now).max(0) as u64)
}

/// Days since the Unix epoch for a civil (proleptic Gregorian) date.
///
/// Howard Hinnant's `days_from_civil` algorithm, valid for any year.
fn days_from_civil(year: i64, month: i64, day: i64) -> i64 {
    let year = if month <= 2 { year - 1 } else { year };
    let era = (if year >= 0 { year } else { year - 399 }) / 400;
    let year_of_era = year - era * 400;
    let day_of_year = (153 * (if month > 2 { month - 3 } else { month + 9 }) + 2) / 5 + day - 1;
    let day_of_era = year_of_era * 365 + year_of_era / 4 - year_of_era / 100 + day_of_year;
    era * 146_097 + day_of_era - 719_468
}

/// Computes the exponential backoff delay for a zero-based attempt index.
///
/// The exponential delay is capped at `max_backoff` and then jittered (see
/// [`jittered`]) so concurrent clients backing off from the same failure do not
/// synchronize their retries into a thundering herd.
fn backoff(policy: &RetryPolicy, attempt: u32) -> Duration {
    let factor = 2u32.saturating_pow(attempt);
    let capped = policy.initial_backoff.saturating_mul(factor).min(policy.max_backoff);
    jittered(capped)
}

/// Applies "equal jitter" to a delay: half the delay is fixed and half is
/// randomized in `[0, delay/2]`, so the result lands in `[delay/2, delay]`.
///
/// Entropy comes from the wall clock's sub-second nanos rather than a `rand`
/// dependency, keeping the transport runtime zero-dependency; perfect randomness
/// is unnecessary — the goal is only to desynchronize retries.
fn jittered(delay: Duration) -> Duration {
    let half = delay / 2;
    let span = half.as_nanos() as u64;
    if span == 0 {
        return delay;
    }
    let entropy = std::time::SystemTime::now()
        .duration_since(std::time::UNIX_EPOCH)
        .map(|elapsed| elapsed.subsec_nanos())
        .unwrap_or(0);
    half + Duration::from_nanos(u64::from(entropy) % (span + 1))
}

/// Renders a parameter value as a query/header/path string via serde.
///
/// Strings serialize without surrounding quotes, scalars use their JSON form,
/// and enums use their `#[serde(rename)]` wire value — so the same helper works
/// for every parameter type without requiring a `Display` impl. Compound values
/// (arrays/objects) fall back to compact JSON.
pub fn scalar_value<T: Serialize>(value: &T) -> String {
    match serde_json::to_value(value) {
        Ok(serde_json::Value::String(text)) => text,
        Ok(serde_json::Value::Null) => String::new(),
        Ok(other) => other.to_string(),
        Err(_) => String::new(),
    }
}

/// Reads a paging count — an offset, a page number, a page size — out of a
/// value the OpenAPI document typed however it liked.
///
/// Spec params come through as `i32`, `i64`, `u32`, `f64`, or even a numeric
/// string, while the pager counts in `u64`, so going through serde is the one
/// type-agnostic way to reach it.
///
/// Deliberately lenient, and deliberately the *same* leniency as the pager's
/// own `number_at`: a fractional or negative value is floored into the unsigned
/// domain rather than discarded. That matters because `paginate()` drops the
/// paging param from the assembled request and re-sends it from the pager's own
/// state — so a discarded value is not "unset", it is lost. A `limit` declared
/// `type: number` and set to `50.0` would otherwise leave the pager advancing by
/// the item count instead of 50, re-fetching an overlapping window the first
/// time a page comes back short; a negative `offset` would leave page one with
/// no offset at all, unlike the same builder's `send()`.
///
/// Infallible by design, matching [`scalar_value`]: `paginate()` returns a bare
/// pager and cannot use `?`.
pub fn paging_count<T: Serialize>(value: &T) -> Option<u64> {
    let count = match serde_json::to_value(value).ok()? {
        serde_json::Value::Number(number) => {
            // Exact `u64` first: a count past f64's exact-integer range would
            // otherwise be rounded on the way through.
            if let Some(exact) = number.as_u64() {
                return Some(exact);
            }
            number.as_f64()?
        }
        serde_json::Value::String(text) => {
            let text = text.trim();
            if let Ok(exact) = text.parse::<u64>() {
                return Some(exact);
            }
            text.parse::<f64>().ok()?
        }
        _ => return None,
    };
    // NaN has no ordering, so `max` would carry it through into an unspecified
    // cast; there is no count it could mean.
    if count.is_nan() {
        return None;
    }
    Some(count.max(0.0) as u64)
}

/// Renders an object query parameter in OpenAPI `deepObject` style: one
/// `name[property]=value` pair per top-level property.
///
/// `null` properties are skipped so an explicitly null field behaves like an
/// unset optional, and nested arrays/objects fall back to compact JSON because
/// the style does not define a deeper nesting. Pairs come out sorted by
/// property name — `serde_json::Map` is a `BTreeMap` unless `preserve_order` is
/// enabled, which this crate deliberately does not pull in — so the query
/// string is stable across runs and machines. The returned values are
/// unencoded: the caller hands them to the query serializer, which
/// percent-encodes the brackets exactly once.
///
/// Infallible by design: a serialization failure yields no pairs rather than an
/// error, matching [`scalar_value`]'s convention. This is load-bearing, not
/// stylistic — `paginate()` returns a bare pager rather than a `Result`, so a
/// `?` here would not compile for a paginated operation carrying a
/// `deepObject` param.
pub fn deep_object_pairs<T: Serialize>(name: &str, value: &T) -> Vec<(String, String)> {
    match serde_json::to_value(value) {
        Ok(serde_json::Value::Object(properties)) => properties
            .into_iter()
            .filter(|(_, property)| !property.is_null())
            .map(|(key, property)| (format!("{name}[{key}]"), scalar_value(&property)))
            .collect(),
        // An explicit null carries nothing to expand, so the param drops out
        // entirely rather than sending an empty pair.
        Ok(serde_json::Value::Null) => Vec::new(),
        // A loosely-typed param can hold a non-object at runtime; degrade to the
        // plain `name=value` shape instead of dropping it, matching how the
        // emitter falls back for styles the runtime does not render.
        Ok(other) => vec![(name.to_string(), scalar_value(&other))],
        // Unreachable for generated models (they all derive Serialize over
        // serde_json-representable types); dropping the param beats panicking.
        Err(_) => Vec::new(),
    }
}

/// Percent-encodes a single path-parameter value.
///
/// Everything outside the RFC 3986 unreserved set is percent-encoded so a value
/// containing `/`, `?`, or spaces cannot alter the request path structure.
pub fn encode_path_param(value: &str) -> String {
    const HEX: &[u8; 16] = b"0123456789ABCDEF";
    let mut encoded = String::with_capacity(value.len());
    for byte in value.bytes() {
        match byte {
            b'A'..=b'Z' | b'a'..=b'z' | b'0'..=b'9' | b'-' | b'.' | b'_' | b'~' => encoded.push(byte as char),
            // Push `%` and the two hex nibbles straight into the buffer; a
            // `format!("%{byte:02X}")` would allocate a `String` per escaped byte.
            _ => {
                encoded.push('%');
                encoded.push(HEX[(byte >> 4) as usize] as char);
                encoded.push(HEX[(byte & 0x0f) as usize] as char);
            }
        }
    }
    encoded
}

#[cfg(test)]
mod tests {
    /// RFC 3986 reference resolution is what a *server-supplied* pagination
    /// link needs, and it differs from the trim-then-join used for paths the
    /// emitter produces. Pinned here because the bug this replaced only showed
    /// up for path-absolute links — absolute ones resolve correctly either way,
    /// so every happy-path fixture missed it.
    #[test]
    fn server_links_resolve_by_rfc_3986_not_by_trimming() {
        let base = url::Url::parse("https://api.example.com/v1/").expect("a static base parses");
        let resolve = |link: &str| base.join(link).map_or_else(|_| link.to_string(), String::from);

        // Path-absolute replaces the base path — it must NOT append to the prefix.
        assert_eq!(
            resolve("/v2/items?cursor=abc"),
            "https://api.example.com/v2/items?cursor=abc"
        );
        // Absolute is used wholesale.
        assert_eq!(
            resolve("https://other.example.com/x?c=1"),
            "https://other.example.com/x?c=1"
        );
        // Relative resolves against the base, prefix intact.
        assert_eq!(
            resolve("items?cursor=abc"),
            "https://api.example.com/v1/items?cursor=abc"
        );
        // The old trim-then-join behavior would have produced this for the
        // path-absolute case; assert we do not.
        assert_ne!(resolve("/v2/items"), "https://api.example.com/v1/v2/items");
    }

    use super::*;

    /// A `Clone` extension value standing in for a per-request policy hint.
    #[derive(Clone, Debug, PartialEq)]
    struct Marker(&'static str);

    #[test]
    fn clone_request_copies_every_part_including_extensions() {
        let mut request = http::Request::builder()
            .method(http::Method::POST)
            .uri("https://api.example.com/v1/items?page=2")
            .header("x-test", "yes")
            .body(SdkBody::from_bytes("payload"))
            .expect("statically valid request parts must build");
        request.extensions_mut().insert(Marker("policy"));

        let clone = clone_request(&request).expect("a buffered body must be replayable");

        assert_eq!(clone.method(), request.method());
        assert_eq!(clone.uri(), request.uri());
        assert_eq!(clone.version(), request.version());
        assert_eq!(clone.headers(), request.headers());
        // Extension propagation is load-bearing: per-request policy hints ride
        // extensions and must survive the per-attempt rebuild.
        assert_eq!(clone.extensions().get::<Marker>(), Some(&Marker("policy")));
    }

    #[test]
    fn rejected_statuses_retry_for_any_method_but_processed_ones_do_not() {
        // 408/429/503 rejected the request without running it, so even a
        // non-idempotent, unkeyed request replays them.
        assert!(should_retry_status(408, false));
        assert!(should_retry_status(429, false));
        assert!(should_retry_status(503, false));
        // Other 5xx may have executed; they need idempotence or a key.
        assert!(!should_retry_status(500, false));
        assert!(should_retry_status(500, true));
        assert!(!should_retry_status(502, false));
        assert!(should_retry_status(504, true));
        // 409 reports a semantic conflict a blind replay cannot resolve.
        assert!(!should_retry_status(409, true));
        // 501 is a permanent not-implemented condition: never retried, even
        // for idempotent or keyed requests.
        assert!(!should_retry_status(501, true));
        assert!(!should_retry_status(501, false));
    }

    /// A filter object standing in for a generated `deepObject` query param.
    #[derive(Serialize)]
    struct Filter {
        status: &'static str,
        limit: u32,
    }

    #[test]
    fn deep_object_pairs_expands_one_pair_per_property() {
        let pairs = deep_object_pairs(
            "filter",
            &Filter {
                status: "active",
                limit: 10,
            },
        );

        // Sorted by property name, not declaration order: `serde_json::Map` is a
        // `BTreeMap` here, which is what keeps the query string reproducible.
        assert_eq!(
            pairs,
            vec![
                ("filter[limit]".to_string(), "10".to_string()),
                ("filter[status]".to_string(), "active".to_string()),
            ]
        );
    }

    #[test]
    fn deep_object_pairs_skips_null_properties_and_json_encodes_nested_values() {
        let value = serde_json::json!({
            "absent": serde_json::Value::Null,
            "nested": { "gte": 1 },
            "list": [1, 2],
            "plain": "yes",
        });

        let pairs = deep_object_pairs("filter", &value);

        // A null property is dropped so it reads as an unset optional, and the
        // style has no deeper nesting to express, so compound values fall back
        // to compact JSON.
        assert_eq!(
            pairs,
            vec![
                ("filter[list]".to_string(), "[1,2]".to_string()),
                ("filter[nested]".to_string(), "{\"gte\":1}".to_string()),
                ("filter[plain]".to_string(), "yes".to_string()),
            ]
        );
    }

    #[test]
    fn paging_count_floors_instead_of_discarding() {
        // A spec is free to type a paging param `number`. Discarding a
        // fractional value would leave the pager advancing by the item count
        // instead of the caller's page size, so it is floored — the same rule
        // the pager's own `number_at` applies to a fractional total.
        assert_eq!(paging_count(&50.0_f64), Some(50));
        assert_eq!(paging_count(&50.9_f64), Some(50));
        // A negative offset clamps to the start of the collection rather than
        // dropping out: `paginate()` has already excluded the param from the
        // assembled request, so `None` here means page one is sent with no
        // offset at all.
        assert_eq!(paging_count(&-5_i64), Some(0));
        // Numeric strings are accepted for the same reason `number_at` accepts
        // them — a looser API may declare a count as a string.
        assert_eq!(paging_count(&"120"), Some(120));
        assert_eq!(paging_count(&" 7.5 "), Some(7));
        // A count past f64's exact-integer range must not be rounded.
        assert_eq!(paging_count(&(u64::MAX)), Some(u64::MAX));
        // Nothing numeric to read: the caller set no usable value.
        assert_eq!(paging_count(&serde_json::Value::Null), None);
        assert_eq!(paging_count(&"soon"), None);
        // Only the string path can carry a NaN — serde_json cannot represent one
        // as a number — and it has no ordering, so `max` would carry it into an
        // unspecified cast rather than clamp it.
        assert_eq!(paging_count(&"NaN"), None);
        assert_eq!(paging_count(&f64::NAN), None);
    }

    #[test]
    fn deep_object_pairs_degrades_for_non_object_values() {
        // A loosely-typed param may hold anything at runtime; a scalar keeps the
        // plain `name=value` shape and a null drops out entirely.
        assert_eq!(
            deep_object_pairs("filter", &serde_json::json!("active")),
            vec![("filter".to_string(), "active".to_string())]
        );
        assert!(deep_object_pairs("filter", &serde_json::Value::Null).is_empty());
    }

    #[test]
    fn style_separators_survive_the_query_serializer_exactly_once() {
        // Both styles hand *unencoded* values to `dispatch`, which appends them
        // through url's form_urlencoded serializer. The separators must come out
        // escaped exactly once, so the server sees one `a|b` value and one
        // `filter[status]` name.
        let joined = ["a", "b"].iter().map(scalar_value).collect::<Vec<_>>().join("|");
        let pairs = deep_object_pairs(
            "filter",
            &Filter {
                status: "active",
                limit: 10,
            },
        );

        let mut url = url::Url::parse("https://api.example.com/v1/items").expect("a static url parses");
        {
            let mut serializer = url.query_pairs_mut();
            serializer.append_pair("tags", &joined);
            for (name, value) in &pairs {
                serializer.append_pair(name, value);
            }
        }

        assert_eq!(
            url.query(),
            Some("tags=a%7Cb&filter%5Blimit%5D=10&filter%5Bstatus%5D=active")
        );
    }

    /// A transport handing out scripted responses in order; the test fails
    /// loudly if more requests arrive than were scripted.
    #[derive(Debug)]
    struct ScriptedTransport {
        responses: std::sync::Mutex<std::collections::VecDeque<http::Response<SdkBody>>>,
        calls: std::sync::atomic::AtomicUsize,
    }

    impl ScriptedTransport {
        fn new(responses: Vec<http::Response<SdkBody>>) -> Self {
            Self {
                responses: std::sync::Mutex::new(responses.into_iter().collect()),
                calls: std::sync::atomic::AtomicUsize::new(0),
            }
        }

        fn calls(&self) -> usize {
            self.calls.load(std::sync::atomic::Ordering::SeqCst)
        }
    }

    impl Transport for ScriptedTransport {
        fn execute(
            &self,
            _request: http::Request<SdkBody>,
        ) -> crate::transport::BoxFuture<'_, Result<http::Response<SdkBody>, TransportError>> {
            self.calls.fetch_add(1, std::sync::atomic::Ordering::SeqCst);
            let response = self
                .responses
                .lock()
                .expect("scripted responses lock")
                .pop_front()
                .expect("a scripted response for every request");
            Box::pin(std::future::ready(Ok(response)))
        }
    }

    /// A sleeper that records requested delays and resolves instantly, so the
    /// tests can assert the exact backoff the retry loop chose.
    #[derive(Debug, Default)]
    struct RecordingSleep(std::sync::Mutex<Vec<Duration>>);

    impl RecordingSleep {
        fn delays(&self) -> Vec<Duration> {
            self.0.lock().expect("recorded delays lock").clone()
        }
    }

    impl Sleep for RecordingSleep {
        fn sleep(&self, duration: Duration) -> crate::transport::BoxFuture<'static, ()> {
            self.0.lock().expect("recorded delays lock").push(duration);
            Box::pin(std::future::ready(()))
        }
    }

    /// Builds a scripted response with a status, optional Retry-After seconds,
    /// and a buffered body.
    fn scripted(status: u16, retry_after: Option<u64>, body: &'static str) -> http::Response<SdkBody> {
        let mut builder = http::Response::builder().status(status);
        if let Some(seconds) = retry_after {
            builder = builder.header(http::header::RETRY_AFTER, seconds.to_string());
        }
        builder
            .body(SdkBody::from_bytes(body))
            .expect("statically valid response parts must build")
    }

    /// Builds a POST request: non-idempotent and unkeyed, the strictest case
    /// for the retry taxonomy.
    fn post_request() -> http::Request<SdkBody> {
        http::Request::builder()
            .method(http::Method::POST)
            .uri("https://api.example.com/v1/items")
            .body(SdkBody::from_bytes("{}"))
            .expect("statically valid request parts must build")
    }

    #[tokio::test]
    async fn retry_after_within_ceiling_sleeps_the_full_server_delay() {
        // 45 s is far past max_backoff (8 s): the server's delay must be
        // honored in full, not clamped back into the same rate-limit window.
        let transport = ScriptedTransport::new(vec![scripted(429, Some(45), "slow down"), scripted(200, None, "{}")]);
        let sleep = RecordingSleep::default();
        let response = send_with_retries(&transport, &sleep, post_request(), 2, None, false)
            .await
            .expect("scripted attempts cannot fail at the transport level");
        assert_eq!(response.status(), 200);
        assert_eq!(transport.calls(), 2);
        assert_eq!(sleep.delays(), vec![Duration::from_secs(45)]);
    }

    #[tokio::test]
    async fn retry_after_beyond_ceiling_returns_the_response_without_retrying() {
        // The server told us to go away for longer than we will wait: the 429
        // is the terminal result, with no sleep and no second attempt.
        let transport = ScriptedTransport::new(vec![scripted(429, Some(61), "come back tomorrow")]);
        let sleep = RecordingSleep::default();
        let response = send_with_retries(&transport, &sleep, post_request(), 2, None, false)
            .await
            .expect("scripted attempts cannot fail at the transport level");
        assert_eq!(response.status(), 429);
        assert_eq!(transport.calls(), 1);
        assert!(sleep.delays().is_empty());
    }

    #[tokio::test]
    async fn possibly_processed_500_is_not_replayed_for_an_unkeyed_post() {
        // The taxonomy's other half: a 500 may have executed the POST, so an
        // unkeyed request must not replay it.
        let transport = ScriptedTransport::new(vec![scripted(500, None, "{}")]);
        let sleep = RecordingSleep::default();
        let response = send_with_retries(&transport, &sleep, post_request(), 2, None, false)
            .await
            .expect("scripted attempts cannot fail at the transport level");
        assert_eq!(response.status(), 500);
        assert_eq!(transport.calls(), 1);
    }

    #[tokio::test]
    async fn oversized_error_body_truncates_but_keeps_the_status() {
        // A 502 serving a body past the cap must stay a diagnosable ApiError
        // (status/headers/request id intact), never Error::ResponseTooLarge.
        let response = http::Response::builder()
            .status(502)
            .header("x-request-id", "req_123")
            .body(SdkBody::from_bytes(vec![b'x'; 64]))
            .expect("statically valid response parts must build");
        let error = decode_json::<serde_json::Value>(response, 16)
            .await
            .expect_err("a 502 must decode to an error");
        match error {
            Error::Api(api) => {
                assert_eq!(api.status, 502);
                assert_eq!(api.request_id.as_deref(), Some("req_123"));
                assert!(api.truncated, "the over-cap body must be marked truncated");
                assert_eq!(api.raw.as_deref(), Some("xxxxxxxxxxxxxxxx"));
            }
            other => panic!("expected Error::Api, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn oversized_success_body_still_fails_with_response_too_large() {
        // The memory-bounding cap is unchanged where it matters: a success
        // body the caller would buffer is rejected, not silently truncated.
        let response = http::Response::builder()
            .status(200)
            .body(SdkBody::from_bytes(vec![b'x'; 64]))
            .expect("statically valid response parts must build");
        let error = decode_json::<serde_json::Value>(response, 16)
            .await
            .expect_err("an over-cap success body must be rejected");
        match error {
            Error::ResponseTooLarge { limit } => assert_eq!(limit, 16),
            other => panic!("expected Error::ResponseTooLarge, got {other:?}"),
        }
    }

    #[tokio::test]
    async fn drain_for_reuse_consumes_small_bodies_and_abandons_large_ones() {
        use std::sync::Arc;
        use std::sync::atomic::{AtomicUsize, Ordering};

        // A small error body is read to the end so the connection stays
        // reusable: every chunk of the stream must be polled.
        let polled = Arc::new(AtomicUsize::new(0));
        let counter = Arc::clone(&polled);
        let small = futures_util::stream::iter((0..4).map(move |_| {
            counter.fetch_add(1, Ordering::SeqCst);
            Ok(Bytes::from_static(b"tiny error body"))
        }));
        drain_for_reuse(SdkBody::from_stream(small)).await;
        assert_eq!(polled.load(Ordering::SeqCst), 4);

        // A body past RETRY_DRAIN_LIMIT abandons the drain partway instead of
        // buffering unboundedly (each chunk below is exactly the limit, so the
        // second chunk tips it over and the rest must never be polled).
        let polled = Arc::new(AtomicUsize::new(0));
        let counter = Arc::clone(&polled);
        let large = futures_util::stream::iter((0..8).map(move |_| {
            counter.fetch_add(1, Ordering::SeqCst);
            Ok(Bytes::from(vec![0u8; RETRY_DRAIN_LIMIT]))
        }));
        drain_for_reuse(SdkBody::from_stream(large)).await;
        assert_eq!(polled.load(Ordering::SeqCst), 2);
    }

    /// Redaction proof for the `tracing` instrumentation. Compiled only with
    /// the feature, since the events do not exist without it.
    #[cfg(feature = "tracing")]
    mod tracing_events {
        use super::*;
        use std::sync::{Arc, Mutex};

        /// A minimal `tracing::Subscriber` that renders every event it sees as
        /// `target message field=value …` text.
        ///
        /// Hand-rolled rather than pulled from `tracing-subscriber`: proving
        /// redaction must not add a dev-dependency to every generated crate.
        #[derive(Clone, Default)]
        struct Capture(Arc<Mutex<Vec<String>>>);

        impl Capture {
            fn rendered(&self) -> String {
                self.0.lock().expect("capture lock").join("\n")
            }
        }

        /// Appends `name=value` for every field of an event, using the `Debug`
        /// fallback so string, integer, and `%`/`?` fields all render.
        struct Render<'a>(&'a mut String);

        impl tracing::field::Visit for Render<'_> {
            fn record_debug(&mut self, field: &tracing::field::Field, value: &dyn std::fmt::Debug) {
                use std::fmt::Write;
                let _ = write!(self.0, " {}={value:?}", field.name());
            }
        }

        impl tracing::Subscriber for Capture {
            fn enabled(&self, _metadata: &tracing::Metadata<'_>) -> bool {
                true
            }

            fn new_span(&self, _span: &tracing::span::Attributes<'_>) -> tracing::span::Id {
                tracing::span::Id::from_u64(1)
            }

            fn record(&self, _span: &tracing::span::Id, _values: &tracing::span::Record<'_>) {}

            fn record_follows_from(&self, _span: &tracing::span::Id, _follows: &tracing::span::Id) {}

            fn event(&self, event: &tracing::Event<'_>) {
                let mut rendered = event.metadata().target().to_owned();
                event.record(&mut Render(&mut rendered));
                self.0.lock().expect("capture lock").push(rendered);
            }

            fn enter(&self, _span: &tracing::span::Id) {}

            fn exit(&self, _span: &tracing::span::Id) {}
        }

        /// Every event the runtime emits for a retried request and a failed
        /// decode, captured on one thread-local subscriber.
        fn capture_request_and_decode_events() -> String {
            let capture = Capture::default();
            let sink = capture.clone();
            tracing::subscriber::with_default(capture, || {
                let runtime = tokio::runtime::Builder::new_current_thread()
                    .build()
                    .expect("a current-thread runtime must build");
                runtime.block_on(async {
                    // An API key in the query string and a bearer token in a
                    // header: the two places credentials actually ride.
                    let request = http::Request::builder()
                        .method(http::Method::GET)
                        .uri("https://api.example.com/v1/items?api_key=super-secret-key&page=2")
                        .header(http::header::AUTHORIZATION, "Bearer super-secret-token")
                        .body(SdkBody::from_bytes("{}"))
                        .expect("statically valid request parts must build");
                    let transport =
                        ScriptedTransport::new(vec![scripted(429, Some(1), "slow down"), scripted(200, None, "{}")]);
                    send_with_retries(&transport, &RecordingSleep::default(), request, 2, None, false)
                        .await
                        .expect("scripted attempts cannot fail at the transport level");

                    // A success body that does not match the target type: the
                    // decode-failure event must not carry the body.
                    let response = http::Response::builder()
                        .status(200)
                        .body(SdkBody::from_bytes(r#"{"api_key":"super-secret-key"}"#))
                        .expect("statically valid response parts must build");
                    decode_json::<u64>(response, 1024)
                        .await
                        .expect_err("an object is not a u64");
                });
                sink.rendered()
            })
        }

        #[test]
        fn events_redact_credentials_and_never_carry_headers_or_bodies() {
            let rendered = capture_request_and_decode_events();

            // The whole point: nothing a caller configured as a credential may
            // reach a log line.
            assert!(
                !rendered.contains("super-secret-key"),
                "query credential leaked: {rendered}"
            );
            assert!(
                !rendered.contains("super-secret-token"),
                "header credential leaked: {rendered}"
            );
            assert!(
                !rendered.contains("authorization"),
                "header names must not be logged: {rendered}"
            );
            // The URL is still there — redacted, not dropped — so the event
            // stays diagnosable.
            assert!(
                rendered.contains("url=https://api.example.com/v1/items?…"),
                "redacted url missing: {rendered}"
            );
            // The retry decision reports where the delay came from.
            assert!(
                rendered.contains("source=\"retry-after\""),
                "retry source missing: {rendered}"
            );
            assert!(
                rendered.contains("status=200 attempts=2"),
                "terminal outcome missing: {rendered}"
            );
            // A decode failure reports a class, never the body that failed.
            assert!(
                rendered.contains("error_class=\"serde\""),
                "decode failure class missing: {rendered}"
            );
        }

        /// The credential-fallback event says what happened and nothing else:
        /// it fires on an auth path, so it must name no credential, no
        /// alternative, and no part of the failed exchange's error.
        #[test]
        fn the_oauth_fallback_event_carries_no_fields() {
            let capture = Capture::default();
            let sink = capture.clone();
            tracing::subscriber::with_default(capture, trace_oauth_fallback);
            let rendered = sink.rendered();
            assert!(
                rendered.contains("oauth token exchange failed"),
                "fallback event missing: {rendered}"
            );
            // `message` is the only `name=value` pair the renderer can print for
            // this event; anything else would be a field carrying auth detail.
            assert_eq!(
                rendered.matches('=').count(),
                1,
                "the event must carry no fields: {rendered}"
            );
        }
    }
}
