// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! API for managing Scalar platform resources.
//!
//! ## TypeScript SDK
//!
//! For TypeScript, we provide a SDK that makes using our API even easier.
//!
//! ### Install
//!
//! ```text
//! npm add @scalar/sdk
//! ```
//!
//! ### Get a Scalar API key
//!
//! Create an API key in your Scalar account:
//!
//! - Dashboard: https://dashboard.scalar.com/account
//! - Store it in `.env`, for example:
//!
//! ```text
//! SCALAR_API_KEY=your_personal_token
//! ```
//!
//! ### Exchange your API key for an access token
//!
//! The personal token is not an access token. Exchange it first with `postv1AuthExchange`.
//!
//! If you use the personal token directly for authenticated API calls, the API returns `401 Invalid authentication token`.
//!
//! ```text
//! import { Scalar } from '@scalar/sdk'
//!
//! const scalar = new Scalar()
//!
//! const exchange = await scalar.auth.postv1AuthExchange({
//!   personalToken: process.env.SCALAR_API_KEY!,
//! })
//!
//! const accessToken = exchange.accessToken
//! ```
//!
//! ### Use the access token
//!
//! Construct a second client with bearer auth. Use this authenticated client for API calls.
//!
//! ```text
//! import { Scalar } from '@scalar/sdk'
//!
//! const scalar = new Scalar()
//!
//! const exchange = await scalar.auth.postv1AuthExchange({
//!   personalToken: process.env.SCALAR_API_KEY!,
//! })
//!
//! const authedScalar = new Scalar({
//!   bearerAuth: exchange.accessToken,
//! })
//! ```
//!
//! ### Notes
//!
//! - The exchange request itself can be made from a client constructed with no arguments (`new Scalar()`).
//! - The exchanged access token is valid for 12 hours.
//! - Timestamps are Unix seconds.
//!
//! ### Read more
//!
//! - [@scalar/sdk on npm](https://www.npmjs.com/package/@scalar/sdk)

pub mod error;
pub mod http;
pub mod models;
pub mod client;
pub mod resources;

pub use models::{AccessGroup, ActiveDeployment, ApiDocument, AuthenticationExchangePersonalTokenBody, AuthenticationExchangePersonalTokenResponse, BadRequestError, Email, ForbiddenError, GithubProject, GithubProjectRepository, InternalServerError, LoginPortal, LoginPortalEmail, LoginPortalPage, LoginPortalsCreateBody, LoginPortalsRetrieveResponse, LoginPortalsUpdateBody, ManagedDocVersion, ManagedDocVersionEmbedStatus, ManagedSchemaVersion, Method, Namespace, Nanoid, NotFoundError, RegistryCreateApiDocumentBody, RegistryCreateApiDocumentResponse, RegistryCreateApiDocumentVersionBody, RegistryUpdateApiDocumentBody, RegistryUpdateApiDocumentVersionBody, RegistryUpdateApiDocumentVersionResponse, Rule, RulesCreateRulesetBody, RulesUpdateRulesetBody, ScalarDocsCreateGuideBody, ScalarDocsCreateGuideResponse, ScalarDocsPublishGuideResponse, Schema, SchemasCreateBody, SchemasUpdateBody, Slug, Team, TeamImage, TeamName, TeamSummary, Theme, ThemesCreateBody, ThemesReplaceDocumentBody, ThemesUpdateBody, Timestamp, Uid, UnauthorizedError, UnprocessableEntityError, User, Version, VersionCreateSchemaBody};
pub use client::Scalar;
pub use client::ScalarBuilder;
pub use client::Environment;
pub use error::{ApiError, Error};

/// The version of this crate, matching the published package version.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
