// Code generated by Scalar SDK Generator. DO NOT EDIT.
#![doc = include_str!("../README.md")]
#![recursion_limit = "512"]

pub mod client;
pub mod error;
#[doc(hidden)]
pub mod http;
pub mod models;
#[doc(hidden)]
pub mod number;
pub mod resources;
pub mod transport;
#[doc(hidden)]
pub mod transport_reqwest;

pub use client::Environment;
pub use client::Scalar;
pub use client::ScalarBuilder;
pub use error::{ApiError, Error};
pub use models::{
    AccessGroup, AccessGroupName, AccessGroupsCreateBody, AccessGroupsCreateResponse, AccessGroupsRetrieveResponse,
    AccessGroupsUpdateBody, ActiveDeployment, ApiDocument, AuthenticationExchangePersonalTokenBody,
    AuthenticationExchangePersonalTokenResponse, BadRequestError, DocsProject, DomainsCreateBody, DomainsDeleteBody,
    Email, EmailDomain, ForbiddenError, GithubProject, GithubProjectRepository, InstallationsCreateAccessGroupBody,
    InstallationsCreateBody, InstallationsDeleteAccessGroupBody, InstallationsUpdateBody, InternalServerError,
    InvitesMemberBody, LoginPortal, LoginPortalEmail, LoginPortalPage, LoginPortalsCreateBody,
    LoginPortalsRetrieveResponse, LoginPortalsUpdateBody, ManagedDocVersion, ManagedDocVersionEmbedStatus,
    ManagedDocVersionTool, ManagedDocVersionToolEnabledTool, ManagedSchemaVersion, McpInstallation,
    McpInstallationListItem, McpServer, MembersListResponse, MembersUpdateBody, Method, Namespace, Nanoid,
    NotFoundError, OAuthOauthTokenResponse, OauthAuthorizationServerMetadata, OauthError, OauthRevokeRequest,
    OauthScope, OauthToken, OauthTokenRequest, RegistryCreateApiDocumentBody, RegistryCreateApiDocumentResponse,
    RegistryCreateApiDocumentVersionBody, RegistryUpdateApiDocumentBody, RegistryUpdateApiDocumentVersionBody,
    RegistryUpdateApiDocumentVersionResponse, RepositoriesLinkBody, RepositoriesLinkBodyLanguage,
    RepositoriesLinkResponse, RepositoriesUpdatePublishingBody, RepositoriesUpdatePublishingBodyAccess,
    RepositoriesUpdatePublishingBodyAuthMethod, Role, Rule, RulesCreateRulesetBody, RulesUpdateRulesetBody,
    ScalarDocsCreateGuideBody, ScalarDocsCreateGuideResponse, ScalarDocsCreateProjectBody,
    ScalarDocsCreateProjectBodyBitbucketRepository, ScalarDocsCreateProjectBodyGithubRepository,
    ScalarDocsCreateProjectBodyProvider, ScalarDocsListProjectConfigResponse, ScalarDocsListProjectDomainResponse,
    ScalarDocsListProjectDomainStatusResponse, ScalarDocsListProjectDomainStatusResponseExpected,
    ScalarDocsListProjectDomainStatusResponseStatus, ScalarDocsListProjectsResponse, ScalarDocsPublishGuideResponse,
    ScalarDocsPublishProjectBody, ScalarDocsPublishProjectResponse, ScalarDocsUpdateProjectBody,
    ScalarDocsUpdateProjectBodyLoginPortalUid, ScalarDocsUpdateProjectConfigBody,
    ScalarDocsUpdateProjectConfigResponse, Schema, SchemasCreateBody, SchemasUpdateBody, Sdk, SdkTargetSummary,
    SdkTargetSummaryLanguage, SdkVersion, SdkVersionLanguage, SdkVersionStatus, SdksBuildBody, SdksBuildBodyLanguage,
    SdksBuildResponse, SdksCreateBody, SdksCreateBodyLanguage, SdksListResponse, SdksUpdateBody, ServersCreateBody,
    ServersCreateResponse, ServersUpdateBody, Slug, Team, TeamImage, TeamInvite, TeamMember, TeamName, TeamSummary,
    Theme, ThemesCreateBody, ThemesReplaceDocumentBody, ThemesUpdateBody, Timestamp, Uid, UnauthorizedError,
    UnprocessableEntityError, User, Version, VersionCreateBody, VersionCreateResponse, VersionsCreateBody,
};

/// The version of this crate, matching the published package version.
pub const VERSION: &str = env!("CARGO_PKG_VERSION");
