// Code generated by Scalar SDK Generator. DO NOT EDIT.
//! Default HTTP backend: `ReqwestTransport`, a `Transport` implementation
//! backed by `reqwest`.
//!
//! Every item in this module is gated on the `reqwest` cargo feature; with
//! `default-features = false` the crate compiles without this backend and the
//! caller supplies their own [`crate::transport::Transport`] implementation.
//!
//! This transport sets no timeouts of its own: the SDK runtime enforces
//! deadlines uniformly by racing the configured sleeper against
//! `Transport::execute`, so no transport — bundled or BYO — can silently drop
//! them. Timers are likewise provided separately: when the `reqwest` feature
//! is enabled the client defaults to the tokio-backed sleeper defined next to
//! the `Transport` trait; this module deliberately does not define one.

// Compile-time guard: reqwest with neither TLS backend cannot speak https, and
// every generated base URL is https — without this the failure would surface
// only at runtime as an opaque connect error. The guard is additive-safe
// (unlike a conflicting-features guard would be): enabling a feature can only
// *satisfy* it, so cargo's feature unification across a dependency tree can
// never break a build that compiles today.
#[cfg(all(feature = "reqwest", not(any(feature = "rustls", feature = "native-tls"))))]
compile_error!(
    "the `reqwest` feature needs a TLS backend: enable the `rustls` or `native-tls` cargo feature (the default feature set includes one)"
);

#[cfg(feature = "reqwest")]
use futures_util::TryStreamExt;

#[cfg(feature = "reqwest")]
use crate::transport::{BoxFuture, SdkBody, Transport, TransportError, TransportErrorKind};

/// The default [`Transport`], backed by a shared [`reqwest::Client`].
///
/// Construct one client and reuse it: cloning is cheap because the inner
/// client is reference-counted, so clones share one connection pool.
#[cfg(feature = "reqwest")]
#[derive(Debug, Clone)]
pub struct ReqwestTransport {
    /// The underlying reqwest client; shared by every clone of this transport.
    client: reqwest::Client,
}

#[cfg(feature = "reqwest")]
impl ReqwestTransport {
    /// Creates a transport with the SDK's opinionated defaults.
    ///
    /// Redirects are **disabled** ([`reqwest::redirect::Policy::none`]): a
    /// followed redirect can silently re-send credentials to an unexpected
    /// host, so the SDK surfaces 3xx responses as data and leaves following
    /// them to the caller. The user agent is deliberately not set here — the
    /// generated client sends its SDK user agent as a regular request header,
    /// so it applies identically to every transport, including BYO ones.
    ///
    /// Use [`ReqwestTransport::from_client`] to supply a customized client
    /// (proxies, TLS options, pool tuning).
    ///
    /// # Errors
    ///
    /// Returns a [`TransportError`] of kind [`TransportErrorKind::Other`] when
    /// the underlying TLS backend or system configuration prevents
    /// constructing a client.
    pub fn new() -> Result<Self, TransportError> {
        let client = reqwest::Client::builder()
            .redirect(reqwest::redirect::Policy::none())
            .build()
            .map_err(|error| TransportError::new(TransportErrorKind::Other, redact_url(error)))?;
        Ok(Self { client })
    }

    /// Wraps an existing [`reqwest::Client`].
    ///
    /// The client is used exactly as configured: **its own redirect policy
    /// applies** (reqwest follows up to 10 redirects by default, unlike
    /// [`ReqwestTransport::new`], which disables them), along with its
    /// proxies, connection pool, and TLS settings. Use this when you need
    /// backend detail the SDK defaults do not expose.
    pub fn from_client(client: reqwest::Client) -> Self {
        Self { client }
    }
}

#[cfg(feature = "reqwest")]
impl Transport for ReqwestTransport {
    fn execute(
        &self,
        request: http::Request<SdkBody>,
    ) -> BoxFuture<'_, Result<http::Response<SdkBody>, TransportError>> {
        Box::pin(async move {
            let request = into_reqwest(&self.client, request)?;
            let response = self.client.execute(request).await.map_err(classify)?;
            Ok(into_response(response))
        })
    }
}

/// Converts an `http` request into a [`reqwest::Request`] bound to `client`.
///
/// Body mapping: a buffered body is handed over as sized bytes so reqwest can
/// send a `Content-Length`; an empty buffered body sends no body at all; a
/// streaming (or retryable-stream) body is forwarded chunk by chunk without
/// buffering. The HTTP version on the request is intentionally not forwarded:
/// pinning it would defeat ALPN negotiation, so reqwest picks the version.
///
/// # Errors
///
/// Returns [`TransportErrorKind::Other`] when the URI cannot be parsed as a
/// URL — a request-construction bug, not a network failure — and a
/// [`classify`]-mapped error when reqwest rejects the assembled request.
#[cfg(feature = "reqwest")]
fn into_reqwest(client: &reqwest::Client, request: http::Request<SdkBody>) -> Result<reqwest::Request, TransportError> {
    let (parts, body) = request.into_parts();
    // `http::Uri` accepts a few shapes `url::Url` rejects (e.g. relative
    // ones); re-parsing keeps the failure here, with a clear kind, instead of
    // deep inside reqwest.
    let url = reqwest::Url::parse(&parts.uri.to_string())
        .map_err(|error| TransportError::new(TransportErrorKind::Other, error))?;
    let mut builder = client.request(parts.method, url).headers(parts.headers);
    builder = match body.as_bytes() {
        // No-body and empty-body are indistinguishable on the wire for the
        // methods this SDK generates, so an empty buffered body sends nothing.
        Some(bytes) if bytes.is_empty() => builder,
        // `Bytes::clone` is a refcount bump, not a copy of the payload.
        Some(bytes) => builder.body(bytes.clone()),
        None => builder.body(reqwest::Body::wrap_stream(body.into_data_stream())),
    };
    builder.build().map_err(classify)
}

/// Converts a [`reqwest::Response`] into the SDK's `http` response shape.
///
/// Status, headers, and HTTP version are copied; the body becomes a lazy
/// [`SdkBody`] stream, so large or streaming responses are never buffered
/// here. A failure while reading the stream surfaces as a [`TransportError`]
/// of kind [`TransportErrorKind::Body`].
#[cfg(feature = "reqwest")]
fn into_response(mut response: reqwest::Response) -> http::Response<SdkBody> {
    let status = response.status();
    let version = response.version();
    let headers = std::mem::take(response.headers_mut());
    let body = SdkBody::from_stream(
        response
            .bytes_stream()
            .map_err(|error| TransportError::new(TransportErrorKind::Body, redact_url(error))),
    );
    // Assembled through the mutators rather than `http::Response::builder()`
    // so the conversion is infallible — the parts came from a valid response.
    let mut converted = http::Response::new(body);
    *converted.status_mut() = status;
    *converted.version_mut() = version;
    *converted.headers_mut() = headers;
    converted
}

/// Classifies a [`reqwest::Error`] into a [`TransportError`].
///
/// This mapping is **load-bearing for retry semantics**: the runtime retries
/// `Connect` failures for any method (the request never reached the server)
/// and `Timeout` failures only for idempotent requests. A transport that
/// lumped everything into `Other` would lose connect-retry, which is why BYO
/// transports are documented with this same table:
///
/// | `reqwest::Error` predicate  | [`TransportErrorKind`] |
/// |-----------------------------|------------------------|
/// | `is_connect()`              | `Connect`              |
/// | `is_timeout()`              | `Timeout`              |
/// | `is_body()` / `is_decode()` | `Body`                 |
/// | anything else               | `Other`                |
#[cfg(feature = "reqwest")]
fn classify(error: reqwest::Error) -> TransportError {
    let kind = if error.is_connect() {
        TransportErrorKind::Connect
    } else if error.is_timeout() {
        TransportErrorKind::Timeout
    } else if error.is_body() || error.is_decode() {
        TransportErrorKind::Body
    } else {
        TransportErrorKind::Other
    };
    TransportError::new(kind, redact_url(error))
}

/// Strips the query string from the URL a [`reqwest::Error`] carries.
///
/// API keys commonly ride query parameters, and `reqwest::Error` includes its
/// URL in `Display`; redacting the query before the error is wrapped means no
/// `Display`/`Debug` of the source can leak credentials, while the host and
/// path survive for debuggability.
#[cfg(feature = "reqwest")]
fn redact_url(mut error: reqwest::Error) -> reqwest::Error {
    if let Some(url) = error.url_mut() {
        url.set_query(None);
    }
    error
}
